const fs=require('fs'),vm=require('vm'),path=require('path');
const file=path.join(__dirname,'..','js','math_10_data.js'),ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const sec=(id,title,page,theory,rules,diagram)=>({id,title,page,theory,rules,...(diagram?{diagram}:{})});
const ex=(n,p,s,problem,given,method,steps,answer,diagram)=>({id:'eg'+n,number:n,page:p,sectionId:s,title:`Example ${n} (p. ${p})`,problem,given,method,steps,answer,...(diagram?{diagram}:{})});
const q=(qNo,question,solution,answer,diagram,options)=>({qNo,question,solution,answer,...(diagram?{diagram}:{}),...(options?{options}:{})});
const set=(exercise,page,problems,title=`Exercise ${exercise}`)=>({exercise,page,title,problems});
const get=n=>ctx.MATH_10_DATA.find(u=>u.number===n);

// Unit 8: theorem proofs and exercises only; the printed unit contains no numbered examples.
{
 const u=get(8);u.status='ready';u.pageRange='Pages 193–201';u.badge='Rebuilt in textbook order from pages 193–201';
 u.description='The projection definition, proofs of Theorems 8.1–8.3, Exercises 8.1–8.2 and Review Exercise 8 follow the scanned textbook sequence.';
 u.sections=[
  sec('8.1','8.1 Projection of a Point and a Line Segment',194,'The projection of a point on a line is its foot of the perpendicular. The projection of a segment is the segment between the projections of its endpoints. The perpendicular distance is the shortest distance from a point to a line.',['Draw a perpendicular from each endpoint to the line; the feet determine the projected segment.'],{type:'right-triangle',title:'A segment and its perpendicular projection'}),
  sec('8.2','8.2 Theorem 8.1 — Obtuse-Angled Triangle',194,'In ΔABC with ∠C obtuse, drop AD perpendicular to BC produced. Let BC=a, AC=b, AB=c and CD=p. By applying Pythagoras to the two right triangles and using segment addition, c²=a²+b²+2ap. The scan gives the theorem together with a formal statements-and-reasons proof and a corollary.',['For an obtuse angle, c²=a²+b²+2a·p, where p is the projection of the side onto the other side produced.','The signed projection is represented by the positive exterior length in the printed diagram.'],{type:'right-triangle',title:'Obtuse triangle with projection on the extended side'}),
  sec('8.3','8.3 Theorem 8.2 — Acute-Angled Triangle',196,'Drop AD perpendicular to BC (or BC produced if needed). The projection length p lies on the side containing the acute angle. Pythagoras and segment addition give c²=a²+b²−2ap. The book proves both the acute and obtuse configurations from the same construction.',['For an acute angle, c²=a²+b²−2a·p.','The sign of the projection term depends on which side contains the perpendicular foot.'],{type:'right-triangle',title:'Acute triangle and projection onto a side'}),
  sec('8.4','8.4 Theorem 8.3 — Apollonius Theorem',198,'If AE is the median to BC, then the sum of the squares on AB and AC equals twice the square on half of BC plus twice the square on the median. The proof drops a perpendicular from A and compares the two right triangles.',['AB²+AC²=2(BE²+AE²), where E is the midpoint of BC.','Use the median formula to find a median or an unknown side.'],{type:'right-triangle',title:'Median and perpendicular in Apollonius theorem'})
 ];
 u.workedExamples=[];
 u.exercises=[
  set('8.1',198,[
   q('1','In ΔABC, AB=6 cm, BC=10 cm and ∠B=120°. The projection of BC on AB is 5 cm. Find AC.','By Theorem 8.1, AC²=6²+10²+2(6)(5)=196.','AC=14 cm',{type:'right-triangle',title:'Obtuse triangle and projected side'}),
   q('2','In ΔABC, AB=3 cm, BC=5 cm and AC=7 cm. Find the projection of BC on AB.','Place A and B on a horizontal line with AB=3. By the cosine rule, the coordinate of C along AB is (AC²+AB²−BC²)/(2AB)=5.5; subtract AB to get the projection of BC.','2.5 cm'),
   q('3','In ΔABC, a=7, b=11 and c=8. Calculate the projection of AC on AB.','The textbook defines a=BC, b=AC and c=AB. Thus p=b cosA=(b²+c²−a²)/(2c)=(11²+8²−7²)/(2·8).','8.5 units'),
   q('4','In a parallelogram ABCD, AB=4 cm, AC=7 cm and AD=5 cm. Find which angles of the parallelogram are obtuse.','In ΔABC, BC=AD=5. By the cosine rule, cos∠B=(AB²+BC²−AC²)/(2·AB·BC)=(16+25−49)/40=−1/5, so ∠B is obtuse. Opposite ∠D is equal to it.','∠B and ∠D are obtuse.')
  ]),
  set('8.2',200,[
   q('1','Using Apollonius theorem, find the lengths of the medians of a triangle having sides 10 cm, 12 cm and 16 cm respectively.','For each median, use mₐ²=(2b²+2c²−a²)/4, taking the opposite side as a.','5√7 cm, √142 cm and √58 cm.'),
   q('2','In ΔABC, D is the midpoint of BC. Find the length of the median if AB=4 cm, BC=5 cm and AC=6 cm.','AD²=(2AB²+2AC²−BC²)/4=(32+72−25)/4=79/4.','AD=√79/2 cm.'),
   q('3','ΔABC is given with BC=4 cm, AC=12 cm and ∠C=120°. Find CD, AD, AB and then verify Apollonius theorem.','Drop AD perpendicular to BC produced. The projection CD=12cos60°=6; AD=12sin60°=6√3; BD=BC+CD=10. Pythagoras gives AB²=BD²+AD²=208. For the median from A to BC, E is the midpoint, BE=2 and AE²=172.','CD=6 cm; AD=6√3 cm; AB=4√13 cm. Apollonius: AB²+AC²=208+144=352=2(2²+172).',{type:'right-triangle',title:'Obtuse triangle with altitude AD'}),
   q('4','ΔABC is a right triangle with ∠B=90° and BD⊥AC. If AB=6 cm and BC=5 cm, find AD and CD. Verify your answer with Pythagorean theorem.','AC=√(6²+5²)=√61. By similarity, AD=AB²/AC and CD=BC²/AC.','AD=36/√61 cm; CD=25/√61 cm; AD+CD=√61 cm.')
  ]),
  set('Review Exercise 8',200,[
   q('(i)','Pythagoras was a/an _____.','Pythagoras was a Greek mathematician.','Greek',null,['Indian','Greek','Pakistani','Chinese']),
   q('(ii)','Apollonius was born in _____.','Apollonius of Perga is associated with Perga.','Perga',null,['Perga','Islamabad','Kabul','Peshawar']),
   q('(iii)','Apollonius is the name of a _____.','Apollonius was a mathematician.','Mathematician',null,['City','Town','Country','Mathematician']),
   q('2','Find the projection of the side of length 10 units onto the side of length 17 units in a triangle with sides 10, 17 and 21 units.','Use the cosine rule to find the projection onto the 17-unit side.','26/17 units ≈1.53 units'),
   q('3','ΔABC is right-angled at A. From A, AD is perpendicular to BC. If AB=5 cm and AC=8 cm, find BC, AD and BD.','BC=√(5²+8²)=√89. By similarity, AD=AB·AC/BC and BD=AB²/BC.','BC=√89 cm; AD=40/√89 cm; BD=25/√89 cm',{type:'right-triangle',title:'Right triangle with altitude to the hypotenuse'}),
   q('4','In the previous question, BE is a median. Find BE using (a) Pythagoras theorem and (b) Apollonius theorem.','The median from B to AC has squared length (2AB²+2BC²−AC²)/4.','BE=√41 cm'),
   q('5','Find x and y in the printed triangle with sides 10, 17 and 19 and altitude h to the 19-unit base.','Use the projection formula x=(10²+19²−17²)/(2·19), then y=19−x and h²=10²−x².','x=86/19≈4.53; y=275/19≈14.47; h≈8.92')
  ],'Review Exercise 8')
 ];
 u.formulaSheet=[{name:'Obtuse triangle theorem',formula:'c²=a²+b²+2ap'},{name:'Acute triangle theorem',formula:'c²=a²+b²−2ap'},{name:'Apollonius theorem',formula:'AB²+AC²=2(AD²+BD²), D midpoint of BC'}];
}

// Unit 9: five printed examples, two exercise sets and the review set.
{
 const u=get(9);u.status='ready';u.pageRange='Pages 202–211';u.badge='Rebuilt in textbook order from pages 202–211';
 u.description='The circle definitions and Theorems 9.1–9.5 precede Examples 1–5, Exercises 9.1–9.2 and Review Exercise 9. Figures use the chord, centre and perpendicular relationships shown in the scan.';
 u.sections=[
  sec('9.1','9.1 One and Only One Circle Through Three Non-Collinear Points',203,'Given three non-collinear points A, B and C, the perpendicular bisectors of two chords meet at the unique centre O. The circle centred at O through any one of the points passes through all three.',['Exactly one circle passes through three non-collinear points.'],{type:'construction-center',title:'Circumcentre of three non-collinear points'}),
  sec('9.2','9.2 Bisector from the Centre to a Chord',204,'If a line from the centre bisects a chord that is not a diameter, it is perpendicular to that chord. The proof uses the congruent triangles formed by the radii, half-chords and shared centre-to-midpoint segment.',['If N is the midpoint of chord AB, then ON⊥AB.']),
  sec('9.3','9.3 Perpendicular from the Centre to a Chord Bisects It',205,'A perpendicular from the centre of a circle to a chord bisects the chord. Congruent right triangles prove the two chord segments are equal.',['If ON⊥AB, then AN=NB.'],{type:'circle-chord',title:'Perpendicular from the centre bisects chord AB'}),
  sec('9.4','9.4 Congruent Chords Are Equidistant from the Centre',207,'Congruent chords of one circle (or congruent circles) have equal perpendicular distances from their centres. Drop perpendiculars from the centres to both chords and compare the resulting right triangles.',['Equal chords in the same or congruent circles are equidistant from the centre.'],{type:'circle-chord',title:'Equal chords and equal centre distances'}),
  sec('9.5','9.5 Chords Equidistant from the Centre Are Congruent',208,'If two chords of one circle are at equal perpendicular distances from the centre, the chords are congruent. The proof uses the perpendicular-bisector theorem and equal radii.',['Equal centre distances imply equal chords.'])
 ];
 u.sections.forEach(s=>{if(!s.diagram)s.diagram={type:'circle-chord',title:s.title};});
 u.workedExamples=[
  ex(1,204,'9.3','In ⊙P, PM⊥AT, PT=10 and PM=8. Find MT.','PT=10; PM=8; PM⊥MT','Pythagoras in right triangle PMT',['MT²=PT²−PM²=100−64=36.','MT=6.'],'6 units',{type:'circle-chord',title:'Perpendicular from centre P to chord AT'}),
  ex(2,205,'9.2','A circle has radius 5 cm. PX=3 cm and PR⊥AB at X. Find AB.','Radius=5 cm; distance PX=3 cm','The perpendicular from the centre bisects the chord',['AX²=5²−3²=16, so AX=4 cm.','AB=2AX=8 cm.'],'8 cm',{type:'circle-chord',title:'Radius perpendicular to chord AB'}),
  ex(3,206,'9.2','In circle R, XY=30, RX=17, and RZ⊥XY. Find the distance from R to XY.','XY=30; RX=17','The perpendicular from the centre bisects the chord',['XZ=XY/2=15.','RZ²=17²−15²=64, so RZ=8.'],'8 units',{type:'circle-chord',title:'Centre-to-chord distance'}),
  ex(4,209,'9.3','In a circle of radius 5 cm, chords ST and RP are each 3 cm from the centre O. Compare their lengths.','r=5 cm; each chord is 3 cm from O','Equal distances from the centre give equal chords',['Half of either chord is √(5²−3²)=4 cm.','Each chord has length 2·4=8 cm.'],'ST=RP=8 cm',{type:'circle-chord',title:'Two equidistant chords'}),
  ex(5,209,'9.3','Two parallel chords of a circle of radius 12 cm have lengths 8 cm and 14 cm. Find their separation.','r=12 cm; chord lengths 8 cm and 14 cm','Find each perpendicular distance from O using a half-chord right triangle',['Distances are √(12²−4²)=√128≈11.31 cm and √(12²−7²)=√95≈9.75 cm.','If on the same side, subtract; if on opposite sides, add.'],'Same side: ≈1.56 cm; opposite sides: ≈21.06 cm',{type:'circle-chord',title:'Parallel chords and distances from centre'})
 ];
 u.exercises=[
  set('9.1',206,[
   q('1','A circle has radius 30 cm. Find the length of a chord 10 cm from the centre.','Chord=2√(r²−d²).','40√2 cm'),
   q('2','A chord is 48 cm long and 18 cm from the centre. Find the diameter.','r²=24²+18².','60 cm'),
   q('3','The diameter of a circle is 5 units. How far from the centre is a chord 4 units long?','r=2.5; d=√(r²−2²).','1.5 units'),
   q('4','A chord 8 cm long is 5 cm from the centre. Find the radius.','r²=5²+4².','√41 cm'),
   q('5','Find the length of a chord 5 cm from the centre of a circle of radius 8 cm.','Chord=2√(8²−5²).','2√39 cm'),
   q('6','In circle Q, QW⊥XY and QT⊥YZ. If QW=QT=5 and YT=12, find XY.','Equal distances from the centre give equal chords. Since QT bisects YZ, the half-chord is 12; therefore the equal chord XY is 24.','24 units',{type:'circle-chord',title:'Equal chords at equal centre distances'})
  ]),
  set('9.2',210,[
   q('1','In a circle of radius 5 cm, two parallel chords have lengths 8 cm and 6 cm. Find the distance between them.','Their distances from O are 3 cm and 4 cm. Depending on placement, subtract or add.','1 cm (same side) or 7 cm (opposite sides)'),
   q('2','Two parallel chords PQ and MN are 3 cm apart on the same side of a circle. PQ=7 cm and MN=14 cm. Find the radius.','Let d be the perpendicular distance to the longer chord. The other is d+3. Use r²=d²+7²=(d+3)²+3.5².','r≈8.39 cm'),
   q('3','A circle with centre C has radius 10. Chord QT is 5 units from C and chord PR is 8 units from C. (a) Compare PR and QT. (b) Compare their distances from C.','The closer chord is longer. Use half-chord lengths √(10²−5²) and √(10²−8²).','(a) QT>PR. (b) PR is farther from C.')
  ]),
  set('Review Exercise 9',210,[
   q('(i)','In a circle, two chords equally distant from the centre are _____.','Chords equally distant from the centre are congruent.','Congruent',null,['Congruent','Not congruent','Parallel','Non-parallel']),
   q('(ii)','In the same circle AB<CD. Which chord is closer to O?','The shorter chord is farther from the centre.','CD is closer to O',null,['AB is closer to O','CD is closer to O','AB must be parallel to CD','Cannot decide']),
   q('(iii)','A chord is 5 cm from the centre of a circle of radius 13 cm. Find its length.','2√(13²−5²)=24.','24 cm',null,['6 cm','12 cm','24 cm','30 cm']),
   q('(iv)','A chord 40 units long lies in a circle of radius 25. Find its distance from the centre.','d=√(25²−20²).','15 units',null,['15','31.2','47.1','50.1']),
   q('(v)','A chord 8√3 units long is 4 units from the centre. Find the radius.','Half-chord=4√3; r²=48+16.','8 units',null,['14.4','8','8√2','2√8']),
   q('(vi)','A circle has radius 5 cm and a chord is 4 cm from O. Find the chord length.','2√(25−16)=6.','6 cm',null,['4 cm','6 cm','7 cm','9 cm']),
   q('(vii)','Radius 5, CE=2, and diameter AC is perpendicular to chord BD at E. Find BD.','OE=OC−CE=3. Half-chord=√(5²−3²)=4.','8',null,['12','10','8','4']),
   q('2','In circle O, OA is a radius and AB⊥OC. Find: (i) AC and AB if AO=13 m and OC=5 m; (ii) radius and diameter if AB=16 cm and its distance from O is 6 cm; (iii) the distance from O to a 30 cm chord when the diameter is 34 cm; (iv) AB if r=25 and its distance from O is 7; (v) OA if AB=10 m and its distance from O is 5 m.','Use the perpendicular-bisector theorem and Pythagoras in each case.','(i) AC=12 m, AB=24 m; (ii) r=10 cm,d=20 cm; (iii) 8 cm; (iv) 48 units; (v) 5√2 m'),
   q('3','The perpendicular bisector of chord XY meets XY at N and the circle at P. If XY=16 cm and NP=2 cm, calculate the radius.','XN=8. Let ON=d; the near radius is d+2 and (d+2)²=d²+8².','17 cm')
  ],'Review Exercise 9')
 ];
 u.formulaSheet=[{name:'Chord and centre distance',formula:'r²=d²+(c/2)²'},{name:'Chord length',formula:'c=2√(r²−d²)'},{name:'Equal chord theorem',formula:'Equal chords ⇔ equal perpendicular distances from the centre'}];
}

// Unit 10: tangents, touching circles, seven examples and both exercises plus review.
{
 const u=get(10);u.status='ready';u.pageRange='Pages 212–224';u.badge='Rebuilt in textbook order from pages 212–224';
 u.sections=[
  sec('10.1','10.1 A Perpendicular at the Outer End of a Radius Is Tangent',213,'If a line is perpendicular to a radius at its endpoint on the circle, the line is tangent at that point. The proof shows every other point on the line is farther from the centre.',['At contact C, OC⊥tangent line.'],{type:'tangent',title:'Tangent perpendicular to radius OC'}),
  sec('10.2','10.2 The Radius to the Point of Contact Is Perpendicular to the Tangent',214,'The radius drawn to the point where a tangent touches a circle is perpendicular to that tangent. The perpendicular gives the shortest distance from the centre to the line.',['If AB is tangent at C, then OC⊥AB.']),
  sec('10.3','10.3 Tangents from the Same External Point Are Equal',215,'Two tangent segments drawn from the same external point to a circle have equal lengths. Compare the two right triangles formed by the radii and tangent segments.',['If PA and PB are tangents from P, then PA=PB.','The line joining P to the centre bisects the angle between the tangents.'],{type:'tangent',title:'Equal tangent segments from external point P'}),
  sec('10.4(a)','10.4(a) Externally Touching Circles',219,'When two circles touch externally, the centres and point of contact are collinear, and the distance between centres equals the sum of the radii.',['OO′=R+r.'],{type:'pair-circles',title:'Externally touching circles'}),
  sec('10.4(b)','10.4(b) Internally Touching Circles',221,'When two circles touch internally, the centres and point of contact are collinear, and the distance between centres equals the difference of the radii.',['OO′=R−r.'],{type:'pair-circles',title:'Internally touching circles'})
 ];
 u.sections.forEach(s=>{if(!s.diagram)s.diagram={type:'tangent',title:s.title};});
 u.workedExamples=[
  ex(1,215,'10.1','CB is tangent to the circle in the figure. Find CD.','AB=5 cm, BC=8 cm; AC is a secant through the centre','Use Pythagoras for AC, then subtract the radius',['AC²=5²+8²=89, so AC=√89≈9.43 cm.','CD=AC−AD=√89−5≈4.43 cm.'],'√89−5 cm ≈4.43 cm',{type:'tangent',title:'Tangent CB and radius at the point of contact'}),
  ex(2,216,'10.3','Global positioning satellites use a tangent range. If AX=16,000 miles, find the range BX.','AX=16,000 miles; AX and BX are tangents from X','Tangents from the same external point are equal',['AX=BX.'],'16,000 miles',{type:'tangent',title:'Equal tangent lengths AX and BX'}),
  ex(3,216,'10.3','QT and QS are tangent segments to circle R. If TR=5 and RQ=13, find QT and QS.','TR=5; RQ=13','Pythagoras in right triangle RQT, then equal tangent lengths',['QT²=13²−5²=144, so QT=12.','QT=QS.'],'QT=QS=12',{type:'tangent',title:'Tangent lengths QT and QS'}),
  ex(4,216,'10.3','In the figure, AB is tangent to the circle with centre O. Given AB=8 cm, BC=5 cm and OA=x cm, find x and ∠AOB.','AB=8; BC=5; OA=x; OB=x+5','Pythagoras in right triangle AOB',['(x+5)²=x²+8², giving 10x=39 and x=3.9.','tan∠AOB=8/3.9, so ∠AOB≈64.0°.'],'x=3.9 cm; ∠AOB≈64.0°',{type:'tangent',title:'Tangent AB and radius OA'}),
  ex(5,217,'10.3','In the adjacent figure, AB and BC are two tangents. Evaluate x.','AB=x²+5; BC=21','Set the two tangent lengths equal',['x²+5=21.','x²=16; take the positive value x=4.'],'x=4',{type:'tangent',title:'Equal tangents AB and BC'}),
  ex(6,220,'10.4(a)','Three circles touch in pairs externally. Prove that the perimeter of the triangle formed by joining their centres equals the sum of the diameters of the circles.','Three circles with radii r₁,r₂,r₃ touch externally in pairs','Express each side of the centre triangle as the sum of the two radii at its ends',['The centre distances are r₁+r₂, r₂+r₃ and r₃+r₁.','Their sum is 2r₁+2r₂+2r₃, the sum of the three diameters.'],'Perimeter = d₁+d₂+d₃',{type:'pair-circles',title:'Three pairwise externally touching circles'}),
  ex(7,222,'10.4(b)','Two circles have radii 9 and 4. Find the length of their line of centres when they are (a) tangent externally, (b) tangent internally, (c) concentric and (d) 5 units apart.','R=9; r=4','Apply the centre-distance rule for each arrangement',['(a) 9+4=13. (b) 9−4=5. (c) 0. (d) 9+5+4=18.'],'(a) 13; (b) 5; (c) 0; (d) 18 units',{type:'pair-circles',title:'Four possible positions of two circles'})
 ];
 u.exercises=[
  set('10.1',217,[
   q('1','Find the tangent length from a point 10 cm from the centre of a circle of radius 6 cm.','t=√(10²−6²).','8 cm'),
   q('2','A tangent from an external point is 8 cm long; the point is 9 cm from the centre. Find the radius.','r²=9²−8².','√17 cm'),
   q('3','A chord AC is extended through C. From external point P, tangent PB is drawn. Prove ∠PBC=∠BAP.','Use the tangent-chord angle theorem and the inscribed-angle theorem on the same intercepted arc.','Proved.'),
   q('4','In each of the three printed figures, AB intersects the circle. Find the marked x using the tangent-radius perpendicular relation and Pythagoras.','Apply OA⊥AB at the point of contact and use the side labels in each figure.','(i) 2 cm; (ii) ≈15.65; (iii) 10',{type:'tangent-grid',title:'Three tangent-length diagrams from Exercise 10.1',items:[{},{external:true},{ }]}),
   q('5','The radius is 8 cm. Two tangents from an external point P make an angle of 60° with each other. Find OP.','The line OP bisects the angle between the tangents; use sin30°=8/OP.','16 cm'),
   q('6','PA and PB are tangents to a circle with centre O. Find x and y in each of the four printed figures.','Use equal tangent segments, radii perpendicular to tangents, and the angle bisector OP.','(i) x=49,y=14; (ii) x=58,y=15; (iii) x=34,y=14.8; (iv) x=35,y=55',{type:'tangent-grid',title:'Four pairs of tangents from external points',items:[{external:true},{external:true},{external:true},{external:true}]}),
   q('7','In the figure below, VA and VB are tangents to P, the radius of the circle is 3 cm and VA=6 cm. Find (i) VB, (ii) AP, (iii) PV and (iv) XY.','Tangents from V are equal. Use the radius–tangent right triangle, then subtract the radius to obtain XY.','(i) 6 cm; (ii) 3 cm; (iii) 3√5 cm; (iv) 3(√5−1) cm',{type:'tangent',title:'Two tangents VA and VB from V'}),
   q('8','In circle N, verify that line l is a tangent.','Check the perpendicular radius at the point where l meets the circle.','l is tangent to the circle.',{type:'tangent',title:'Line l tangent to circle N'}),
   q('9','Verify that AB is tangent to the circle at B.','The centre-to-contact radius and AB form a right triangle; verify the Pythagorean relation.','AB is tangent at B.',{type:'tangent',title:'Verify tangent AB at B'}),
   q('10','If AD, DE and BE are tangents to the circle as shown, prove AD+BE=DE.','Tangent segments from each external point are equal. Split DE at the top contact point and substitute the equal pairs.','AD+BE=DE',{type:'tangent',title:'Three tangents enclosing a circle'})
  ]),
  set('10.2',222,[
   q('1','Two circles have radii 8 cm and 3 cm and touch externally. Find the distance between their centres.','OO′=R+r.','11 cm'),
   q('2','The centres of two internally touching circles are 5 cm apart. If the larger radius is 17 cm, find the smaller radius.','OO′=R−r.','12 cm'),
   q('3','In a circle, a 10 cm long chord is 12 cm from the centre. What is the length of a chord at a distance of 5 cm from the centre?','The first chord gives r²=12²+5²=169, so r=13 cm. For the second chord, half-length=√(13²−5²)=12 cm.','24 cm'),
   q('4','A chord 18 cm long is in a circle of radius 15 cm. Find the distance from the centre to the chord midpoint.','d=√(15²−9²).','12 cm'),
   q('5','Find the length of a chord 6 cm from the centre of a circle of radius 10 cm.','c=2√(10²−6²).','16 cm'),
   q('6','A chord is 8 cm long and 3 cm from the centre. Find the circle’s diameter.','r²=4²+3².','10 cm'),
   q('7','A circle has radius 8 cm and a chord 12 cm long. Find the chord’s distance from the centre.','d=√(8²−6²).','2√7 cm'),
   q('8','A chord 9 cm long is in a circle of radius 7.5 cm. Find its distance from the centre.','d=√(7.5²−4.5²).','6 cm')
  ]),
  set('Review Exercise 10',223,[
   q('(i)','In the figure, ACB is called _____.','ACB denotes the intercepted arc.','An arc',null,['An arc','A secant','A chord','A diameter']),
   q('(ii)','If OT is a radius to the point of contact and PQ is tangent, then _____.','A radius to the point of contact is perpendicular to a tangent.','OT⊥PQ',null,['OT⊥PQ','OT∥PQ','OT⊥ bisector of PQ','OT is a tangent']),
   q('(iii)','Two tangents drawn from the same external point are ____ in length.','Tangent segments from a common external point are equal.','Equal',null,['Half','Equal','Triple','Different']),
   q('(iv)','If two circles touch externally, the distance between their centres is _____.','For external tangency, centre distance is the sum of radii.','The sum of their radii',null,['The difference of radii','The sum of radii','Zero','Twice the larger radius']),
   q('2','In the diagram, B is a point of tangency. Find the radius r of circle C.','Use the marked tangent and secant lengths with the tangent–secant theorem.','39 ft',{type:'tangent-grid',title:'Tangent and secant diagram in feet',items:[{external:true,value:'feet'}]}),
   q('3','In the figure, BP is tangent to the circle with centre O. Given ∠APO=33°, find ∠PBA.','Use the isosceles triangle formed by the radii, the tangent–radius right angle and the angle sum in triangle PBA.','24°',{type:'tangent-grid',title:'Tangent BP and chord PA',items:[{external:true,value:'33°'}]}),
   q('4','O is the centre of the circle through A and B. TA is tangent at A and TB is a secant. Given ∠AOT=64°, find (i) ∠ATB and (ii) ∠TAB.','OA⊥TA. In triangle AOT, the remaining angle is 180°−90°−64°=26°. Use the secant and triangle angle relations for ∠TAB.','(i) 26°; (ii) 122°',{type:'tangent-grid',title:'Tangent TA and secant TB',items:[{external:true},{external:true}]}),
   q('5','Given PA and PB are tangents to the circles with centre O, find the values of the unknowns in (a) and (b).','In (a), use the 5 m radius and 12 m tangent to find OP=13 m, then the external segment i=OP−5. In (b), (k+7)²=k²+15²; use the right triangle for angle r.','(a) i=8 m, j≈67.4°; (b) k=88/7 cm≈12.6 cm, r≈50°',{type:'tangent-grid',title:'The two tangent diagrams from Review Exercise 10',items:[{external:true},{external:true}]})
  ],'Review Exercise 10')
 ];
 u.formulaSheet=[{name:'Radius and tangent',formula:'Radius ⟂ tangent at point of contact'},{name:'Equal tangents',formula:'PA=PB from the same external point P'},{name:'External touching circles',formula:'OO′=R+r'},{name:'Internal touching circles',formula:'OO′=R−r'}];
}

// Unit 11: arcs and chords, including all three printed examples.
{
 const u=get(11);u.status='ready';u.pageRange='Pages 225–237';u.badge='Rebuilt in textbook order from pages 225–237';
 u.sections=[
  sec('11.1','11.1 Congruent Arcs Have Equal Corresponding Chords',227,'In one circle or congruent circles, congruent arcs subtend equal chords. The proof joins the arc endpoints to the centres and uses equal radii and central angles.',['Congruent arcs ⇒ congruent corresponding chords.'],{type:'inscribed-angle',title:'Equal arcs and corresponding chords'}),
  sec('11.2','11.2 Equal Chords Have Congruent Corresponding Arcs',229,'In one circle or congruent circles, equal chords subtend congruent minor arcs, major arcs and semicircles. This is the converse of Theorem 11.1.',['Equal chords ⇒ congruent corresponding arcs.']),
  sec('11.3','11.3 Equal Chords Subtend Equal Central Angles',232,'Equal chords in the same or congruent circles subtend equal angles at their corresponding centres. Compare the triangles made by the two radii and chord.',['If AB=CD, then ∠AOB=∠COD.'],{type:'circle-chord',title:'Equal chords and equal central angles'}),
  sec('11.4','11.4 Equal Central Angles Subtend Equal Chords',234,'If two chords in the same or congruent circles subtend equal central angles, the chords are congruent. The proof uses the two radii and included central angle.',['If ∠AOB=∠COD, then AB=CD.'])
 ];
 u.sections.forEach(s=>{if(!s.diagram)s.diagram={type:'inscribed-angle',title:s.title};});
 u.workedExamples=[
  ex(1,231,'11.1','A point P on the circumference is equidistant from radii OA and OB. Prove that minor arcs AP and BP are equal.','OP is the common side; the perpendicular distances from P to OA and OB are equal','Compare the right triangles formed by the radii and perpendiculars',['The two right triangles have equal hypotenuse OP and equal perpendicular legs.','They are congruent by RHS; the corresponding central angles and arcs are equal.'],'m⌢AP=m⌢BP',{type:'inscribed-angle',title:'Equal distances from P to the two radii'}),
  ex(2,235,'11.2','The internal bisector of central angle AOB meets the circle at P. Prove that arc AP=arc BP.','OP bisects ∠AOB','Compare triangles OAP and OBP',['OA=OB (radii), OP is common, and ∠AOP=∠POB.','The triangles are congruent by SAS, so AP=BP.','Equal chords subtend equal arcs.'],'⌢AP=⌢BP',{type:'inscribed-angle',title:'Angle bisector divides a circle arc'}),
  ex(3,235,'11.2','Tell whether the red arcs in each printed diagram are congruent. Explain.','Three marked diagrams (a)–(c)','Compare their central angles and determine whether the circles are the same or congruent',['(a) Equal central angles in the same circle give congruent arcs.','(b) Equal central angles alone do not make arcs in different-sized, non-congruent circles congruent.','(c) Equal central angles in congruent circles give congruent arcs.'],'(a) yes; (b) no; (c) yes',{type:'inscribed-angle',title:'Comparing arcs in three circle diagrams'})
 ];
 u.exercises=[
  set('11',236,[
   q('1','Given that O is the centre of each of the six circles, find x and y in each printed diagram (i)–(vi).','Use the perpendicular from the centre to a chord, equal chord relationships, Pythagoras and the central angle in each diagram.','(i) x=12,y=90°; (ii) x=11,y=90°; (iii) x=12,y≈67.4°; (iv) x=11,y≈61.9°; (v) x=16,y≈53.1°; (vi) x=6,y≈50.2°',{type:'circle-chord-grid',title:'Six chord and central-distance diagrams',items:[{labels:['x','y']},{labels:['x','y']},{labels:['x','y']},{labels:['x','y']},{labels:['x','y']},{labels:['x','y']}] }),
   q('2','In ⊙Q, KL=LM. If CK=2x+3 and CM=4x, find x.','Equal chords are equidistant from the centre. Since QL passes through C, the two chord halves are equal: CK=CM.','2x+3=4x, so x=1.5.')
  ]),
  set('Review Exercise 11',236,[
   q('(i)','OP has radius 3 and chord AB subtends a 90° central angle. What is the length of AB?','The isosceles triangle OAB has two radius sides of 3 and included angle 90°.','3√2',null,['3√2','6','3√3','9']),
   q('(ii)','In the accompanying diagram of circle O, AB=CD. Which statement is true?','The printed equality is between the two chords.','AB=CD',null,['AB=CD','AB∥CD','AC=BD','∠ABC=∠BCD']),
   q('2','In a circle, two perpendicular diameters are drawn. Show that joining their endpoints in order forms a square.','The four chords are equal because they subtend equal 90° central angles. Each interior angle subtends a diameter and is 90°.','The quadrilateral is a square.',{type:'inscribed-angle',title:'Square formed by endpoints of perpendicular diameters'}),
   q('3','In a circle with centre O, AC is a diameter and ∠AOB=130°. Find ∠ADB, ∠BDC and m⌢BC.','∠ADB subtends arc AB, so it is half 130°. Since AC is a diameter, ∠AOC=180° and ∠BOC=50°. Then ∠BDC is half arc BC.','∠ADB=65°; ∠BDC=25°; m⌢BC=50°',{type:'inscribed-angle',title:'Diameter AC and central angle 130°'}),
   q('4','Chords AB and CD meet at E outside the circle. Prove (a) ∠A=∠C, (b) ∠1=∠2 and (c) ΔADE and ΔCBE are equiangular.','Inscribed angles standing on the same arc are equal: ∠A=∠C. The marked angles 1 and 2 stand on the same chord AC. The exterior lines give equal corresponding angles at E, so the two triangles have three equal angle pairs.','(a) ∠A=∠C; (b) ∠1=∠2; (c) ΔADE∼ΔCBE.',{type:'inscribed-angle',title:'Two secants meeting outside a circle'})
  ],'Review Exercise 11')
 ];
 u.formulaSheet=[{name:'Arc and chord',formula:'Equal arcs ⇔ equal chords'},{name:'Central angle',formula:'Equal chords ⇔ equal central angles'},{name:'Circle angle sum',formula:'A complete central turn is 360°'}];
}

// Unit 12: inscribed angles, segments and cyclic quadrilaterals.
{
 const u=get(12);u.status='ready';u.pageRange='Pages 238–249';u.badge='Rebuilt in textbook order from pages 238–249';
 u.sections=[
  sec('12.1','12.1 Central Angle and Inscribed Angle',239,'The measure of a central angle is twice the measure of an inscribed angle subtended by the same arc (Theorem 12.1).',['Central angle = 2 × inscribed angle on the same arc.','Inscribed angle = half the central angle.'],{type:'inscribed-angle',title:'Central and inscribed angles on the same arc'}),
  sec('12.2','12.2 Angles in the Same Segment',241,'Angles subtended by the same chord at the circumference are equal. The proof draws radii to the chord endpoints and applies Theorem 12.1.',['Inscribed angles standing on the same chord are equal.']),
  sec('12.3(a)','12.3(a) Angle in a Semicircle',242,'An angle inscribed in a semicircle is a right angle (Theorem 12.3(a)).',['The angle subtended by a diameter at the circumference is 90°.'],{type:'inscribed-angle',title:'Right angle in a semicircle'}),
  sec('12.3(b)','12.3(b) Angle in a Segment Greater Than a Semicircle',243,'If the segment is greater than a semicircle, the inscribed angle is less than a right angle (Theorem 12.3(b)).',['An angle in a segment greater than a semicircle is acute.']),
  sec('12.3(c)','12.3(c) Angle in a Segment Less Than a Semicircle',244,'If the segment is less than a semicircle, the inscribed angle is greater than a right angle (Theorem 12.3(c)).',['An angle in a segment less than a semicircle is obtuse.']),
  sec('12.4','12.4 Opposite Angles of a Cyclic Quadrilateral',245,'Opposite angles of any quadrilateral inscribed in a circle are supplementary (Theorem 12.4). The proof uses the central-angle relationships and the 360° angle sum around the centre.',['Opposite angles of a cyclic quadrilateral sum to 180°.','An exterior angle equals the opposite interior angle.'],{type:'inscribed-angle',title:'Cyclic quadrilateral and supplementary opposite angles'})
 ];
 u.sections.forEach(s=>{if(!s.diagram)s.diagram={type:'inscribed-angle',title:s.title};});
 u.workedExamples=[
  ex(1,241,'12.1','A circle has radius √2 cm and chord AB=2 cm. Prove that the angle in the larger segment is 45°.','OA=OB=√2; AB=2','Find the central angle, then halve it',['OA²+OB²=2+2=4=AB²; triangle AOB is right-angled at O.','The central angle ∠AOB=90°.','The inscribed angle standing on AB is half of 90°.'],'45°',{type:'inscribed-angle',title:'Chord of length 2 in a circle of radius √2'}),
  ex(2,244,'12.2','Find a in the printed circle diagram.','Angles ∠ACB and ∠ADB stand on chord AB','Angles in the same segment are equal',['The marked angle in the same segment is 80°.'],'a=80°',{type:'inscribed-angle',title:'Angles subtended by the same chord'}),
  ex(3,245,'12.2','Find each variable in the printed circle with central angle 104° and inscribed angles a° and 2x°.','Central angle=104°','Apply the central-angle theorem and the same-segment theorem',['2a=104°, so a=52°.','2x=52°, so x=26°.'],'a=52°; x=26°',{type:'inscribed-angle',title:'Central angle and inscribed angles'}),
  ex(4,246,'12.3','O is the centre of the circle. Find the unknowns x and y in the cyclic quadrilateral.','Opposite pairs include x with 85° and y with 110°','Opposite angles of a cyclic quadrilateral are supplementary',['x+85°=180°, so x=95°.','y+110°=180°, so y=70°.'],'x=95°; y=70°',{type:'inscribed-angle',title:'Opposite angles in a cyclic quadrilateral'})
 ];
 u.exercises=[
  set('12',247,[
   q('1','O is the centre of the circle. Find the unknown angles x and y in the printed diagram, where the central angle is 70°.','An inscribed angle standing on the same arc is half the central angle; use the straight-angle relation for the remaining angle.','x=35°; y=145°',{type:'inscribed-angle',title:'Inscribed angles from a 70° central angle',centralAngle:70,inscribedAngle:35}),
   q('2','A regular hexagon is inscribed in a circle. Each side is 5√3 units from the centre. Find the radius.','The perpendicular from the centre bisects a side; use a 30°–60°–90° triangle.','10 units'),
   q('3','Find the value of each variable in the two printed cyclic-quadrilateral diagrams (a) and (b).','Opposite angles of a cyclic quadrilateral sum to 180°. In (a), c+(2c−6)=180 and 10x+8x=180. In (b), each opposite pair is supplementary.','(a) c=62°, x=10°; (b) a=45°, b=30°',{type:'inscribed-angle-grid',title:'Two cyclic quadrilaterals with marked angles',items:[{labels:['c°','10x°','(2c−6)°','8x°']},{labels:['2a°','2b°','2a°','4b°']}]}),
   q('4','Show that a parallelogram inscribed in a circle is a rectangle.','Opposite angles in a parallelogram are equal; opposite angles in a cyclic quadrilateral are supplementary. Equal supplementary angles are each 90°.','Every angle is 90°, so the parallelogram is a rectangle.')
  ]),
  set('Review Exercise 12',248,[
   q('(i)','In the figure, O is the centre of the circle, ∠TPR=80° and ∠QOR=x°. Find x.','The angle adjacent to ∠TPR is 100°. Use the inscribed-angle theorem to obtain the corresponding central angle.','160°',{type:'inscribed-angle',title:'Central angle and exterior inscribed angle',centralAngle:160,inscribedAngle:80},['80°','160°','100°','120°']),
   q('(ii)','In the diagram, ∠ADC is a central angle and m∠ADC=60°. What is m∠ABC?','Use the central-angle and inscribed-angle relation for the intercepted arc.','30°',{type:'inscribed-angle',title:'Central angle 60° and inscribed angle',centralAngle:60,inscribedAngle:30},['15°','60°','120°','30°']),
   q('(iii)','In the figure, O is the centre and ∠PQR=70°. Calculate x, the reflex central angle marked in the figure.','The minor central angle subtending the same arc PR is 2×70°=140°. The marked reflex angle is 360°−140°=220°.','220°',{type:'inscribed-angle',title:'Inscribed angle 70° and reflex central angle',centralAngle:220,inscribedAngle:70},['140°','220°','290°','110°']),
   q('(iv)','In the figure, ∠SPT=100°, ∠PQS=40° and ∠PRQ=x°. Calculate x.','Use the cyclic-quadrilateral angle and same-segment relations.','40°',{type:'inscribed-angle',title:'Cyclic quadrilateral with angles 100° and 40°',inscribedAngle:40},['20°','40°','50°','60°']),
   q('(v)','If the marked central angle m∠3=75°, find m∠1 and m∠2.','Each inscribed angle standing on the same arc is half the central angle: 75°÷2=37½°.','37½°, 37½°',{type:'inscribed-angle',title:'Two inscribed angles on the same arc',centralAngle:75,inscribedAngle:37.5},['37½°,37½°','37½°,75°','75°,37½°','75°,75°']),
   q('(vi)','Given O is the centre, find the marked x in the circle.','The inscribed angle is half the central angle standing on the same arc.','50°',{type:'inscribed-angle',title:'Central and inscribed angles in Review Exercise 12 (vi)',centralAngle:100,inscribedAngle:50},['12½°','25°','50°','75°']),
   q('(vii)','Given O is the centre, find the marked y in the circle.','Angles standing on the same chord are equal; apply the inscribed-angle theorem.','25°',{type:'inscribed-angle',title:'Angles in the same segment in Review Exercise 12 (vii)',inscribedAngle:25},['12½°','25°','50°','75°']),
   q('(viii)','In the figure, O is the centre. Find x.','The central angles are 140° and 120°; subtract them from 360°.','100°',{type:'inscribed-angle',title:'Isosceles triangles in a circle with 20° and 30° base angles',centralAngle:100,inscribedAngle:20},['50°','75°','100°','125°']),
   q('2','O is the centre of the circle. Find the unknowns in both printed diagrams (i) and (ii).','Use opposite angles of a cyclic quadrilateral and angles in the same segment.','(i) x=98°, y=60°; (ii) x=38°, y=25°',{type:'inscribed-angle-grid',title:'Two circle diagrams for Review Exercise 12 question 2',items:[{labels:['x','y','given angles']},{labels:['x','y','given angles']}]}),
   q('3','ABCD is a quadrilateral circumscribed about a circle. Show that m⌢AB+m⌢CD=m⌢BC+m⌢DA.','Each arc is twice the angle between the corresponding tangents; combine the equal tangent lengths and angle sums.','Proved.'),
   q('4','Find x in each of the six printed circle diagrams.','Use central angles, inscribed angles, same-segment equality and cyclic-quadrilateral supplementary angles.','(i) x=80°; (ii) x=125°; (iii) x=50°; (iv) x=45°; (v) y=12°; (vi) x=70°',{type:'inscribed-angle-grid',title:'Six circle angle diagrams from Review Exercise 12 question 4',items:[{labels:['x','given angles']},{labels:['x','given angles']},{labels:['x','given angles']},{labels:['x','given angles']},{labels:['x','given angles']},{labels:['x','given angles']}]})
  ],'Review Exercise 12')
 ];
 u.formulaSheet=[{name:'Central and inscribed angles',formula:'Central angle = 2 × inscribed angle on the same arc'},{name:'Angle in a semicircle',formula:'90°'},{name:'Cyclic quadrilateral',formula:'Opposite angles sum to 180°'}];
}

// Unit 13 is a construction chapter; its work is presented as ordered procedures rather than numbered examples.
{
 const u=get(13);u.status='ready';u.pageRange='Pages 250–269';u.badge='Rebuilt in textbook order from pages 250–269';
 u.description='Construction procedures follow subsections 13.1.1–13.3.7, followed by Exercises 13.1–13.3 and Review Exercise 13. The scanned book presents constructions rather than numbered worked examples.';
 u.sections=[
  sec('13.1.1','13.1.1 Locate the Centre of a Given Circle',251,'Choose three points A, B and C on the circumference. Join them; the perpendicular bisectors of two chords meet at O, the centre.',['The perpendicular bisectors of chords pass through the centre.'],{type:'construction-center',title:'Centre found from two chord bisectors'}),
  sec('13.1.2','13.1.2 Draw a Circle Through Three Non-Collinear Points',252,'Join A, B and C in pairs. Construct the perpendicular bisectors of AB and AC; their intersection is O. With centre O and radius OA, draw the unique circle through all three points.',['Three non-collinear points determine exactly one circle.'],{type:'construction-center',title:'Circle through three non-collinear points'}),
  sec('13.1.3(a)','13.1.3(a) Complete an Arc by Finding Its Centre',252,'Choose a third point C on the given arc AB. Construct the perpendicular bisectors of AC and BC; their intersection is O. With radius OA, draw the complete circle.',['Find the centre from two chord bisectors, then set the compass to the centre-to-arc radius.'],{type:'construction-center',title:'Complete an arc after locating its centre'}),
  sec('13.1.3(b)','13.1.3(b) Complete an Arc Without Finding Its Centre',253,'Choose successive points on the given arc and use the compass to step off equal chords, constructing a sequence of points around the rest of the circumference. Continue the curve smoothly through those points to complete the circle.',['Equal chords of one circle subtend equal arcs.'],{type:'construction-circle',title:'Continue an arc by stepping off equal chords'}),
  sec('13.2.1','13.2.1 Circumscribe a Circle About a Given Triangle',253,'Construct perpendicular bisectors of two sides of triangle ABC. Their intersection O is the circumcentre. With centre O and radius OA, draw the circle through A, B and C.',['The circumcentre is equidistant from all three vertices.'],{type:'triangle-circle',title:'Circumcircle about triangle ABC'}),
  sec('13.2.2','13.2.2 Inscribe a Circle in a Given Triangle',254,'Bisect two interior angles. Their intersection O is the incentre. Drop OD perpendicular to a side; with centre O and radius OD, draw the incircle.',['The incentre is equidistant from all three sides.'],{type:'triangle-circle',title:'Incircle in triangle ABC'}),
  sec('13.2.3','13.2.3 Escribe a Circle Opposite a Given Vertex',254,'Extend the sides through A to form exterior angles. Bisect the angles at A, B and C as shown; their intersection O is the excentre opposite A. Drop OF perpendicular to AB and draw the circle with radius OF.',['The escribed circle opposite A touches BC and the extensions of AB and AC.'],{type:'triangle-circle',title:'Escribed circle opposite vertex A'}),
  sec('13.2.4','13.2.4 Circumscribe an Equilateral Triangle About a Circle',255,'Mark three points A, T and U that divide the circumference into equal arcs (central angles 120°). Draw perpendiculars to OA, OT and OU at the three points; the tangent lines meet to form the circumscribed equilateral triangle.',['The three contact points divide the circle into equal arcs.'],{type:'triangle-circle',title:'Equilateral triangle circumscribed about a circle'}),
  sec('13.2.5','13.2.5 Inscribe an Equilateral Triangle in a Given Circle',256,'Draw a diameter AD. With centre D and radius OD, mark points B and C where the arcs meet the circle. Join A to B and C.',['The three vertices cut the circumference into equal arcs.'],{type:'triangle-circle',title:'Equilateral triangle inscribed in a circle'}),
  sec('13.2.6','13.2.6 Circumscribe a Square About a Given Circle',256,'Draw perpendicular diameters AB and CD. Draw perpendicular tangent lines at their four endpoints; the four intersections form the circumscribed square EFGH.',['A tangent is perpendicular to the radius at its point of contact.'],{type:'construction-square',title:'Square circumscribed about a circle'}),
  sec('13.2.7','13.2.7 Inscribe a Square in a Given Circle',257,'Draw perpendicular diameters AB and CD. Join their endpoints consecutively to form the inscribed square ACBD.',['The diagonals of the inscribed square are perpendicular diameters.'],{type:'construction-square',title:'Square inscribed in a circle'}),
  sec('13.2.8','13.2.8 Circumscribe a Regular Hexagon About a Given Circle',258,'Step off six equally spaced points A–F on the circle using the radius as compass width. Draw the three diameters through opposite points, then construct a tangent at each of the six points. Their consecutive intersections form the circumscribed regular hexagon.',['The six contact points are equally spaced.'],{type:'construction-hexagon',title:'Regular hexagon circumscribed about a circle'}),
  sec('13.2.9','13.2.9 Inscribe a Regular Hexagon in a Given Circle',258,'Choose A on the circle. With compass width equal to the radius, step off six consecutive points around the circumference. Join consecutive points to form ABCDEF.',['Each side of an inscribed regular hexagon equals the circle radius.'],{type:'construction-hexagon',title:'Regular hexagon inscribed in a circle'}),
  sec('13.3.1(i)','13.3.1(i) Draw a Tangent at the Midpoint of an Arc Without Its Centre',259,'Draw a chord AB through the given midpoint P. At P, construct a perpendicular to AB; that perpendicular is the tangent.',['The tangent at the midpoint of an arc is perpendicular to the chord through that midpoint.'],{type:'tangent',title:'Tangent at the midpoint of an arc'}),
  sec('13.3.1(ii)','13.3.1(ii) Draw a Tangent at an Arc Endpoint Without Its Centre',260,'Choose Q on arc AP and draw chords AP and PQ. Join A to Q. At P, copy ∠PAQ to form ∠QPT; PT is the required tangent.',['Copy the angle in the alternate segment.'],{type:'tangent',title:'Tangent at endpoint P using an angle copy'}),
  sec('13.3.1(iii)','13.3.1(iii) Draw a Tangent Through a Point Outside an Arc Without Its Centre',260,'Join A to the external point P; let the line meet the arc at B. Bisect AP at D and draw a semicircle on AP as diameter. Construct BC perpendicular to AP to meet it at C. With centre P and radius PC, mark E on the given arc and draw PE.',['The auxiliary semicircle provides the right angle needed for the tangent construction.'],{type:'tangent',title:'Tangent from an external point to a given arc'}),
  sec('13.3.2(i)','13.3.2(i) Draw a Tangent at a Point on the Circle',260,'Join centre O to point P. At P, draw a perpendicular to OP; this line is the tangent.',['The tangent at P is perpendicular to radius OP.'],{type:'tangent',title:'Tangent at point P on the circle'}),
  sec('13.3.2(ii)','13.3.2(ii) Draw Tangents from an External Point',261,'With P as centre and radius PO, draw an arc. With O as centre and the circle diameter as radius, draw another arc meeting it at E. Join OE to meet the circle at F, then draw PF.',['The tangent from P touches the circle at F.'],{type:'tangent',title:'Tangent from an external point P'}),
  sec('13.3.3','13.3.3 Draw Two Tangents Meeting at a Given Angle',261,'Draw a diameter AB. At O construct ∠BOD equal to the given angle θ. At D draw DE perpendicular to OD and at A draw AG perpendicular to OA. Their intersection H gives the two tangents DH and AH, which meet at angle θ.',['The angle between two tangents and the corresponding central angle are supplementary.'],{type:'tangent',title:'Two tangents meeting at a prescribed angle'}),
  sec('13.3.4(i)','13.3.4(i) Draw Direct Common Tangents to Two Equal Circles',262,'Join the centres O and P. Draw equal perpendicular offsets at the centres to locate the contact points A and B. Join A to B and extend the line.',['The direct common tangent is parallel to the line joining centres.'],{type:'pair-circles',title:'Direct common tangent to equal circles'}),
  sec('13.3.4(ii)','13.3.4(ii) Draw Transverse Common Tangents to Two Equal Circles',262,'Join OP and bisect it at C. Bisect CP at D; draw a semicircle on CP as diameter and mark E on the circle. Join EP, draw OF parallel to EP, then join EF and extend it as the transverse common tangent.',['The auxiliary right triangle locates the equal tangent direction.'],{type:'pair-circles',title:'Transverse common tangent to equal circles'}),
  sec('13.3.5(i)','13.3.5(i) Draw a Direct Common Tangent to Two Unequal Circles',263,'Join centres O and P. Construct the auxiliary semicircle and the reduced-radius arc described in the scan to locate the tangent direction. Transfer that direction by a parallel through P; joining the contact points gives the direct common tangent.',['Use the difference of the radii in the auxiliary construction.'],{type:'pair-circles',title:'Direct common tangent to unequal circles'}),
  sec('13.3.5(ii)','13.3.5(ii) Draw a Transverse Common Tangent to Two Unequal Circles',264,'Join and extend the line of centres. Use the sum of the radii to construct the auxiliary semicircle, locate the tangent direction with the bisector arc, then transfer the parallel through the smaller-circle centre. Join the two contact points.',['Use the sum of the radii in the auxiliary construction.'],{type:'pair-circles',title:'Transverse common tangent to unequal circles'}),
  sec('13.3.6(a)','13.3.6(a) Draw a Tangent to Two Unequal Touching Circles',265,'Join the centres O and P; the line passes through contact point T. At T draw a perpendicular to OP. This is the common tangent.',['The common tangent at the touching point is perpendicular to the line of centres.'],{type:'pair-circles',title:'Tangent to two unequal touching circles at point T'}),
  sec('13.3.6(b)','13.3.6(b) Draw a Tangent to Two Unequal Intersecting Circles',265,'Join the centres and construct the auxiliary semicircle and radii shown in the figure. The construction locates the tangent contact points on both circles; join and extend them to obtain the common tangent.',['The auxiliary semicircle produces a right angle at the constructed contact point.'],{type:'pair-circles',title:'Common tangent to intersecting circles'}),
  sec('13.3.7(i)','13.3.7(i) Draw a Circle Which Touches Both the Arms of a Given Angle',266,'Bisect ∠ABC. Choose O on the bisector and drop OF perpendicular to BC. With centre O and radius OF, draw the circle; it touches both arms.',['The centre lies on the angle bisector and is equally distant from both arms.'],{type:'angle-circle',title:'Circle tangent to both arms of an angle'}),
  sec('13.3.7(ii)','13.3.7(ii) Draw a Circle Which Touches Two Converging Lines and Passes Through a Given Point Between Them',267,'Bisect the angle between the lines. Draw an auxiliary circle centred on the bisector, then use the given point and the auxiliary circle to locate the centre of the required circle.',['The centre of the required circle lies on the angle bisector.'],{type:'angle-circle',title:'Circle tangent to two lines and passing through a given point'})
 ];
 const constructions={
  '13.1.1':['A circle without mentioning its centre.','To locate the centre of the given circle.',['Choose any three points A, B and C on its circumference.','Join A to B and A to C.','Draw the perpendicular bisectors of AB and AC; they intersect at O.','O is the required centre.']],
  '13.1.2':['Three non-collinear points A, B and C in a plane.','To draw the circle passing through A, B and C.',['Join A to B and A to C.','Draw the perpendicular bisectors of AB and AC; their intersection is O.','With centre O and radius OA (or OB or OC), draw the circle.']],
  '13.1.3(a)':['A part AB of the circumference of a circle.','To complete the circle by finding its centre.',['Choose a point C on the given arc AB so that AC and BC can be drawn.','Find the midpoints of AC and BC and construct their perpendicular bisectors ℓ₁ and ℓ₂.','Their intersection O is the centre of the required circle.','With centre O and radius OA (or OB or OC), draw the circle.']],
  '13.1.3(b)':['A part AC of the circumference of a circle.','To complete the circle without finding its centre.',['Take any point B on the arc AC.','Join AB, BC and AC.','With C as centre and radius AB draw an arc; with B as centre and radius AC draw an arc meeting it at D.','Join BD and CD. With D as centre and radius BC draw an arc; with C as centre and radius BD draw an arc meeting it at E.','Join CD and DE. With E as centre and radius CD draw an arc; with D as centre and radius CE draw an arc meeting it at F.','Continue the same process to obtain points G, H, … approaching A on the required circumference.','Join the sequence of points by freehand arcs to complete the circle.']],
  '13.2.1':['A triangle ABC.','To circumscribe a circle about the given triangle.',['Draw triangle ABC.','Construct perpendicular bisectors of AB and BC; they meet at O.','With centre O and radius OA (or OB or OC), draw the circle.']],
  '13.2.2':['A triangle ABC.','To inscribe a circle in the given triangle.',['Draw the bisectors of two angles of the triangle; they meet at O.','From O draw OD perpendicular to AB.','With centre O and radius OD, draw the circle.']],
  '13.2.3':['A triangle ABC.','To draw an escribed circle opposite vertex A.',['Produce AB and AC to form exterior angles CBD and BCE.','Draw the bisectors of ∠BAC, ∠CBD and ∠BCE; they meet at O.','Draw OF perpendicular to AB.','With centre O and radius OF, draw the circle touching BC and the produced sides.']],
  '13.2.4':['A circle with centre O.','To circumscribe an equilateral triangle about the circle.',['Take A on the circumference and join OA.','At O construct ∠AOT=120° and ∠TOU=120°.','A, T and U divide the circumference into three equal arcs.','Draw perpendiculars to OA, OT and OU at A, T and U.','Their pairwise intersections form the required equilateral triangle.']],
  '13.2.5':['A circle with centre O.','To inscribe an equilateral triangle in the circle.',['Draw a diameter AD.','With D as centre and radius DO, draw arcs meeting the circle at B and C.','Join AB and AC. Triangle ABC is the required equilateral triangle.']],
  '13.2.6':['A circle with centre O.','To circumscribe a square about the circle.',['Draw a diameter AB.','Draw another diameter CD perpendicular to AB.','At A, B, C and D draw perpendiculars to the diameters.','The four tangent lines meet at E, F, G and H; EFGH is the required square.']],
  '13.2.7':['A circle with centre O.','To inscribe a square in the circle.',['Draw a diameter AB.','Draw another diameter CD perpendicular to AB.','Join AC, CB, BD and DA. ACBD is the required inscribed square.']],
  '13.2.8':['A circle with centre O.','To circumscribe a regular hexagon about the circle.',['Take A on the circumference. With A as centre and radius OA, draw arcs meeting the circle at B and F.','Repeat from B and F to mark C and E, then mark D.','Draw diameters AD, BE and CF.','At A, B, C, D, E and F draw perpendiculars to the respective diameters.','The six tangent lines meet consecutively to form the required regular hexagon.']],
  '13.2.9':['A circle with centre O.','To inscribe a regular hexagon in the circle.',['Take A on the circumference.','With A as centre and radius OA, draw arcs meeting the circle at B and F.','Repeat around the circumference to mark C, D and E.','Join AB, BC, CD, DE, EF and FA. ABCDEF is the required hexagon.']],
  '13.3.1(i)':['An arc whose midpoint is P.','To draw the tangent at P without using the centre.',['Draw chord AB with P the midpoint of the arc AB.','Draw the perpendicular from the midpoint P to AB to locate the centre line.','At P draw the perpendicular to that centre line; this is the required tangent.']],
  '13.3.1(ii)':['An arc AP with endpoint P.','To draw a tangent to the arc at P without using the centre.',['Take Q on arc AP and draw chords AP and PQ.','Join A to Q.','At P construct ∠QPT equal to ∠PAQ.','PT is the required tangent.']],
  '13.3.1(iii)':['An arc and a point P outside the arc.','To draw a tangent through P without using the centre.',['Join A to P; the line meets the arc at B. Bisect AP at D.','With D as centre and DP as radius, draw a semicircle on AP.','Draw BC perpendicular to AP to meet the semicircle at C.','With P as centre and PC as radius, draw an arc meeting the given arc at E.','Join PE; PE is the required tangent.']],
  '13.3.2(i)':['A circle with centre O and a point P on its circumference.','To draw a tangent to the circle at P.',['Draw OP.','At P draw a perpendicular to OP.','This perpendicular is the required tangent.']],
  '13.3.2(ii)':['A circle with centre O and an external point P.','To draw a tangent to the circle from P.',['With P as centre and radius PO draw an arc.','With O as centre and the circle diameter as radius, draw an arc meeting the first arc at E.','Join OE; it meets the circle at F.','Draw PF. PF is the required tangent.']],
  '13.3.3':['A circle with centre O and a given angle θ.','To draw two tangents meeting at angle θ.',['Draw a diameter AB.','At O construct ∠BOD=θ.','At D draw DE perpendicular to OD; at A draw AG perpendicular to OA.','The perpendiculars meet at H.','DH and AH are the required tangents.']],
  '13.3.4(i)':['Two equal circles with centres O and P.','To draw a direct (external) common tangent.',['Join OP.','At O and P draw perpendiculars to OP, meeting the circles at A and B.','Join AB and extend it in both directions. AB is the required direct common tangent.']],
  '13.3.4(ii)':['Two equal circles with centres O and P.','To draw a transverse (internal) common tangent.',['Join OP and bisect it at C. Bisect CP at D.','Draw a semicircle on CP as diameter and mark E on it.','Join EP. Through O draw OF parallel to EP.','Join EF and extend the line; it is the required transverse common tangent.']],
  '13.3.5(i)':['Two unequal circles with centres O and P.','To draw a direct (external) common tangent.',['Join OP; it meets the circles at R and S. Bisect OP at Q.','With Q as centre and QP as radius, draw a semicircle.','On the larger circle choose T so that arc RT equals the radius of the smaller circle.','With O as centre and OT as radius draw an arc meeting the semicircle at L.','Join OL to meet the larger circle at M. Through P draw PN parallel to OM.','Join MN and extend it; MN is the required tangent.']],
  '13.3.5(ii)':['Two unequal circles with centres O and P, with r₁>r₂.','To draw a transverse (internal) common tangent.',['Join OP and produce it in both directions. Draw a segment AB whose length is r₁+r₂.','With O as centre and radius AB, draw a semicircle.','Bisect OP at C. With C as centre and radius OC, draw an arc meeting the semicircle at Q.','Draw OQ to meet the larger circle at T. Through P draw PS parallel to OQ in the opposite direction; it meets the smaller circle at S.','Join TS and extend it in both directions. TS is the required transverse common tangent.']],
  '13.3.6(a)':['Two unequal circles touching at T, with centres O and P.','To draw their common tangent.',['Join O and P; OP passes through T.','At T draw a perpendicular to OP. This is the common tangent.']],
  '13.3.6(b)':['Two unequal intersecting circles with centres O and P.','To draw a common tangent to the given circles.',['Join OP and produce it to the right. Draw PQ as a radius of the smaller circle so that PQ is not along OP. Draw OR, a radius of the larger circle, parallel to PQ.','Join RQ and produce it to meet OP produced at S. Bisect OS at T and draw a semicircle on OS as diameter; it cuts the larger circle at L.','Join S and L and produce the line to M. SM is the required tangent.']],
  '13.3.7(i)':['An angle ∠ABC with vertex B and arms AB and BC.','To draw a circle touching both arms of the angle.',['Draw BD, the bisector of ∠ABC.','Take any point O on BD and draw OF perpendicular to BC.','With O as centre and OF as radius, draw the circle. It touches both arms.']],
  '13.3.7(ii)':['Two converging lines LA and KC meeting at B, and a point D between them.','To draw a circle touching both lines and passing through D.',['Draw BE, the bisector of ∠ABC.','Take F on BE and draw FG perpendicular to BC. With F as centre and FG as radius, draw an auxiliary circle.','Join D to B; DB cuts the auxiliary circle at H. Join FH and draw DO parallel to FH.','With O as centre and OD as radius, draw the required circle.']]
 };
 u.sections.forEach(s=>{const construction=constructions[s.id];if(construction)s.construction={given:construction[0],required:construction[1],steps:construction[2]};});
 u.workedExamples=[];
 u.exercises=[
  set('13.1',256,[
   q('1','Construct a triangle with sides 2 cm, 2.5 cm and 3 cm. Also draw its circumcircle.','Construct the triangle by SSS; bisect two sides perpendicularly to locate the circumcentre; draw the circle.','Construction.'),
   q('2','Construct ΔABC with AB=3 cm, AC=4 cm and ∠A=60°. Draw its circumcircle.','Construct the two sides and included angle; locate the circumcentre using perpendicular bisectors.','Construction.'),
   q('3','Construct a triangle with side lengths 3 cm, 4 cm and 6 cm. Draw its inscribed circle.','Construct by SSS; intersect two angle bisectors and use the perpendicular distance to a side as radius.','Construction.'),
   q('4','Construct ΔABC with AB=5 cm, BC=6 cm and CA=8 cm. Draw perpendicular bisectors of its sides and then its circumcircle.','Construct the triangle, find the circumcentre, and draw the circumcircle.','Construction.'),
   q('5','Construct a triangle ABC with ∠A=60° and ∠B=45°. Draw the three angle bisectors and then its incircle.','Construct the triangle from the two angles and a chosen side as shown; locate the incentre and radius.','Construction.'),
   q('6','An equilateral triangle is inscribed in a circle. Find the altitude if the radius is (i) 3, (ii) 4, (iii) 6 and (iv) 12 units. Deduce a result.','For an equilateral triangle, its circumradius R=2h/3, so h=3R/2.','Altitudes: 4.5, 6, 9 and 18 units; h=3r/2.'),
   q('7','An equilateral triangle is circumscribed about a circle. Find its altitude if the radius is (i) 2, (ii) 5 and (iii) 10 units. Deduce a result.','The circle radius is the triangle inradius r=h/3.','Altitudes: 6, 15 and 30 units; h=3r.'),
   q('8','Circumscribe an equilateral triangle about circles of radii 2, 3 and 1 inches.','Draw three tangents with equal 120° central spacing.','Construction.'),
   q('9','Construct a triangle with sides 2.5 cm, 3.5 cm and 4.5 cm. Draw an escribed circle touching the longest side.','Construct by SSS, find the excentre opposite the required side and the perpendicular radius.','Construction.'),
   q('10','For the triangle in Q9, draw an escribed circle touching the smallest side.','Locate the corresponding excentre and use the perpendicular distance to the side.','Construction.')
  ]),
  set('13.2',261,[
   q('1','Circumscribe a square about a circle of radius 5 cm.','Draw perpendicular diameters and tangent lines at their endpoints.','Construction.'),
   q('2','Inscribe a square in a circle of radius 6 cm.','Draw perpendicular diameters and join the four endpoints.','Construction.'),
   q('3','Draw a square of side 6 cm. Circumscribe a circle about it and inscribe a circle in the same square. Measure the radii of these two circles.','The circumradius is half the diagonal; the inradius is half the side.','Circumradius=3√2 cm; inradius=3 cm.'),
   q('4','Draw a circle of suitable radius so that a square circumscribed about it has side length 8 units.','The circle is the incircle of the square, so its diameter equals the square side.','Radius=4 units.'),
   q('5','Inscribe a square of side 10 cm in a circle. What is the radius?','The square diagonal is the circle diameter: d=10√2.','r=5√2 cm.'),
   q('6','Inscribe a regular hexagon in a circle of radius 4 cm.','Step the radius around the circumference six times and join adjacent points.','Each side is 4 cm.'),
   q('7','Construct a circle of radius 4 cm and draw a regular hexagon about the circle.','Mark six equally spaced tangent points and draw tangent lines at them.','Construction.'),
   q('8','Draw a circle of radius 8 cm. Circumscribe and inscribe regular hexagons; find their areas and compare.','For the inscribed hexagon each side is r. For the circumscribed hexagon, the circle radius is the apothem and each side is 2r/√3.','Inscribed area=96√3 cm²; circumscribed area=128√3 cm².'),
   q('9','Draw two regular hexagons with perimeters 6 cm and 30 cm. Find their centres and draw a perpendicular from each centre to one side. What is the relation between the perpendiculars?','For a regular hexagon the apothem is (√3/2) times its side. The side lengths are 1 cm and 5 cm.','The perpendiculars are in the ratio 1:5.'),
   q('10','Can you construct a square whose area equals the area of a given circle? Discuss in detail.','A square with the same area would need side r√π. Exact straightedge-and-compass construction would require constructing √π, which is impossible because π is transcendental.','No exact straightedge-and-compass construction; only an approximation.')
  ]),
  set('13.3',267,[
   q('1','Draw an arc of length 7 cm. Without using its centre, construct a tangent through P when P is (i) the middle of the arc, (ii) an endpoint, and (iii) outside the arc.','Follow the three chord-and-angle constructions shown in subsection 13.3.1.','Construction.'),
   q('2','Draw a circle through point D and tangent to line BC at D.','Construct a perpendicular to BC at D; choose the centre on that perpendicular and draw the circle through D.','Construction.'),
   q('3','Describe a circle of radius 4 cm through point C and tangent to straight line AB.','The centre lies on the line parallel to AB at distance 4 cm and on the circle of radius 4 cm centred at C.','Construct the intersection centre(s) and draw the circle(s).'),
   q('4','A circle has radius 2.5 cm. Point Q is 5 cm from its centre. Draw a tangent from Q to the circle.','Construct the midpoint of OQ, draw the auxiliary circle on diameter OQ, and join Q to an intersection point.','Two tangent segments.'),
   q('5','Two circles have radii 2 cm and 3 cm and their centres are 8 cm apart. Draw direct common tangents.','Use the auxiliary circle with radius difference 1 cm to determine the tangent direction, then draw parallel tangents.','Construction.'),
   q('6','Two congruent circles of radius 4 cm have centres 10 cm apart. Draw transverse common tangents.','Use the midpoint/auxiliary circle construction for equal radii and transfer the tangent lines.','Construction.'),
   q('7','Two circles have radii 2 cm and 2.5 cm; their centres are 5.5 cm apart. Draw transverse common tangents.','Use the auxiliary circle with radius sum 4.5 cm to locate the common tangent direction.','Construction.'),
   q('8','Draw ΔABC with ∠B=60°. Construct a circle of radius 2.5 cm tangent to both arms of the angle.','Locate the centre on the angle bisector at perpendicular distance 2.5 cm from each arm.','Construction.')
  ]),
  set('Review Exercise 13',268,[
   q('(i)','The measure of an exterior angle of a regular hexagon is _____.','360°/6=60°=π/3.','π/3',null,['π/3','π/4','π/6','None']),
   q('(ii)','Tangents drawn at the endpoints of a diameter are _____.','Both tangent lines are perpendicular to the same diameter, so they are parallel.','Parallel',null,['Parallel','Perpendicular','Intersecting','None']),
   q('(iii)','How many tangents can be drawn from a point outside a circle?','There are two points of contact.','2',null,['1','2','3','4']),
   q('(iv)','If the distance between the centres of two circles equals the sum of their radii, the circles _____.','This is the condition for external tangency.','Touch externally',null,['Intersect','Do not intersect','Touch externally','Touch internally']),
   q('2','Practically find the centre of arc ABC.','Use perpendicular bisectors of two chords of the arc.','Construction.'),
   q('3','Escribe a circle opposite vertex A of ΔABC with AB=5 cm, BC=4 cm and CA=3 cm. Find its radius also.','The triangle is right-angled at C. Its exradius opposite A is area/(s−a), with a=BC=4 and area=6.','Radius=6/(6−4)=3 cm.'),
   q('4','Circumscribe a circle about an equilateral triangle ABC with side 5 cm.','Construct perpendicular bisectors; the circumradius is a/√3.','R=5/√3 cm.'),
   q('5','Circumscribe a regular hexagon about a circle of radius 4 cm.','Construct six equally spaced tangents.','Construction.'),
   q('6','Construct a circle of radius 3 cm and draw two tangents making an angle of 60° with each other.','The line joining the centre to the external vertex bisects the 60° angle; set the perpendicular distance to a tangent equal to 3 cm.','Construction.'),
   q('7','Draw two equal circles of radius 3.5 cm whose centres are 7 cm apart. Draw their transverse common tangents.','The circles touch externally; use the common point and the tangent perpendicular to the line of centres.','Construction.'),
   q('8','Draw two common tangents to two intersecting circles of radii 2.5 cm and 3.5 cm.','Use the external common tangent construction from subsection 13.3.5.','Construction.'),
   q('9','Draw two common tangents to two externally touching circles of radii 3 cm and 4 cm.','Use the common point of contact and the direct common-tangent construction.','Construction.')
  ],'Review Exercise 13')
 ];
 u.formulaSheet=[{name:'Circumcentre',formula:'Intersection of perpendicular bisectors of triangle sides'},{name:'Incentre',formula:'Intersection of interior angle bisectors'},{name:'Circle tangent to both arms',formula:'Centre lies on the angle bisector'},{name:'Regular polygon exterior angle',formula:'360°/n'}];
}

fs.writeFileSync(file,'// KPK Grade 10 Mathematics - textbook sequence and content\n// Source: Khyber Pakhtunkhwa Textbook Board Peshawar (Class 10)\nvar MATH_10_DATA = '+JSON.stringify(ctx.MATH_10_DATA,null,2)+';\n');
