// Khyber Pakhtunkhwa Textbook Board Mathematics 2 (Curriculum 2020).
// Structured lesson/practice content is transcribed and reorganised from scans;
// large scans remain outside the site bundle.
function math2Section(id,title,theory,theoryUrdu,rules,rulesUrdu){return{id,title,theory,theoryUrdu,rules,rulesUrdu};}
function math2Problem(num,question,solution,finalAnswer){return{num,question,solution,finalAnswer,steps:[solution],method:'Show your working'};}
function math2Chapter(number,title,titleUrdu,pageRange,sections,examples,exercises,slos,formulaSheet){return{number,id:'u'+number,title,titleUrdu,status:'ready',badge:'Class 2 Workbook Matched',pageRange,description:'Textbook-aligned lessons, examples, solved exercises and exam-style revision for Class 2.',sections,workedExamples:examples,exercises,slos,formulaSheet};}

var MATH_2_DATA = [
math2Chapter(1,'Whole Numbers','کامل اعداد','Pages 1–28',[
 math2Section('1.1','Ordinal Numbers','Ordinal numbers tell the position of an object: first (1st), second (2nd), third (3rd), and so on up to twentieth (20th).','ترتیبی اعداد کسی چیز کا مقام بتاتے ہیں: پہلا، دوسرا، تیسرا اور اسی طرح بیسویں تک۔',['Use ordinal numbers for positions in a line or sequence.','The last two letters help identify ordinal numerals: 1st, 2nd, 3rd.'],['قطار یا ترتیب میں مقام بتانے کے لیے ترتیبی اعداد استعمال کریں۔','ترتیبی عدد کی علامت دیکھیں، جیسے ۱st، ۲nd، ۳rd۔']),
 math2Section('1.2','Counting, Reading and Writing to 999','Read and write numbers up to 999. Three-digit numbers have hundreds, tens and ones. After 999 comes 1000, the first four-digit number.','۹۹۹ تک اعداد پڑھیں اور لکھیں۔ تین ہندسوں والے عدد میں سیکڑے، دہائیاں اور اکائیاں ہوتی ہیں۔ ۹۹۹ کے بعد ۱۰۰۰ آتا ہے جو پہلا چار ہندسوں والا عدد ہے۔',['Count hundreds, then tens, then ones.','1000 is one more than 999.'],['پہلے سیکڑے، پھر دہائیاں اور پھر اکائیاں گنیں۔','۱۰۰۰، ۹۹۹ سے ایک زیادہ ہے۔']),
 math2Section('1.3','Place Value','In 426, 4 is in the hundreds place and has value 400; 2 is in the tens place and has value 20; 6 is in the ones place and has value 6. So 426 = 400 + 20 + 6.','۴۲۶ میں ۴ سیکڑوں کی جگہ پر ہے اور اس کی قیمت ۴۰۰ ہے؛ ۲ دہائیوں کی جگہ پر ہے اور اس کی قیمت ۲۰ ہے؛ ۶ اکائیوں کی جگہ پر ہے۔ ۴۲۶ = ۴۰۰ + ۲۰ + ۶۔',['Read digits from hundreds to ones.','A digit’s place tells its value in the number.'],['ہندسوں کو سیکڑوں سے اکائیوں تک پڑھیں۔','عدد میں ہندسے کی جگہ اس کی قیمت بتاتی ہے۔']),
 math2Section('1.4','Comparing and Ordering Numbers','Compare hundreds first, then tens, then ones. Use >, < or =. Arrange numbers in increasing order from smallest to largest and decreasing order from largest to smallest.','پہلے سیکڑوں، پھر دہائیوں اور پھر اکائیوں کا موازنہ کریں۔ >، < یا = استعمال کریں۔ بڑھتی ترتیب چھوٹے سے بڑے اور گھٹتی ترتیب بڑے سے چھوٹے عدد تک ہوتی ہے۔',['Compare digits from left to right.','For backward counting, subtract one at each step.'],['ہندسوں کا بائیں سے دائیں موازنہ کریں۔','پیچھے گنتی کرتے وقت ہر مرحلے پر ایک کم کریں۔']),
 math2Section('1.5','Counting in Tens, Hundreds and Backward','Count forward or backward in steps of 10 or 100. For example, counting in hundreds gives 100, 200, 300, …, 1000.','۱۰ یا ۱۰۰ کے وقفوں سے آگے یا پیچھے گنیں۔ مثلاً سیکڑوں میں گنتی ۱۰۰، ۲۰۰، ۳۰۰، …، ۱۰۰۰ ہے۔',['In tens, the tens digit changes by one (with regrouping as needed).','In hundreds, add or subtract 100 each time.'],['دہائیوں میں ہر بار ۱۰ جمع یا منہا کریں۔','سیکڑوں میں ہر بار ۱۰۰ جمع یا منہا کریں۔'])
],[
 {id:'m2e1',title:'Hundreds, Tens and Ones',problem:'Write 583 in expanded form and name the value of 8.',given:'583',method:'Use the place of each digit.',steps:['5 hundreds = 500.','8 tens = 80.','3 ones = 3.'],answer:'583 = 500 + 80 + 3; the value of 8 is 80.'},
 {id:'m2e2',title:'Compare and Order',problem:'Arrange 218, 281 and 182 in increasing order.',given:'218, 281, 182',method:'Compare hundreds, then tens.',steps:['All have 2 hundreds.','Compare tens: 8 tens, 1 ten, 8 tens; 182 is first.','Compare 218 and 281 by tens: 218 is smaller.'],answer:'182, 218, 281'}
],[{exercise:'1.1',title:'Exercise 1.1 — Whole Numbers',problems:[
 math2Problem('Q1','Write 347 in expanded form.','347 = 300 + 40 + 7.','300 + 40 + 7'),math2Problem('Q2','What is the value of 6 in 562?','6 is in the tens place, so its value is 60.','60'),math2Problem('Q3','Complete: 390, 400, 410, __.','Add 10 each time: 390, 400, 410, 420.','420'),math2Problem('Q4','Arrange 206, 260 and 602 from greatest to smallest.','602 has 6 hundreds; 260 has 2 hundreds; 206 has 2 hundreds and fewer tens.','602, 260, 206'),math2Problem('Q5','What number comes after 999?','999 + 1 = 1000.','1000')]}],{
 mcqs:[{q:'What is the value of 5 in 352?',options:['5','50','500','352'],correct:1,exp:'5 is in the tens place, so it has value 50.'},{q:'Which is the first four-digit number?',options:['999','100','1000','101'],correct:2,exp:'1000 is one more than 999.'},{q:'Which number is greatest?',options:['438','483','348','384'],correct:1,exp:'All have 4 hundreds; 483 has the most tens.'},{q:'What is the ordinal form of 3?',options:['3rd','3th','3st','thirds'],correct:0,exp:'The ordinal form is 3rd, read “third.”'}],
 shortQuestions:[{q:'Write 704 in expanded form.',sol:'704 = 700 + 0 tens + 4 = 700 + 4.'},{q:'What comes before 500?',sol:'499 comes before 500.'},{q:'Write the ordinal number for twentieth.',sol:'Twentieth is written as 20th.'}],
 longQuestions:[{q:'Explain the place value of each digit in 639.',marks:4,rubric:'Identify hundreds, tens and ones and give expanded form.',sol:'6 is in the hundreds place, so it is 600. 3 is in the tens place, so it is 30. 9 is in the ones place, so it is 9. Therefore 639 = 600 + 30 + 9.'},{q:'Arrange 405, 450 and 504 in increasing order and explain.',marks:3,rubric:'Compare hundreds, then tens and give the correct order.',sol:'405 and 450 have 4 hundreds; 405 has fewer tens. 504 has 5 hundreds and is greatest. Increasing order: 405, 450, 504.'}]},[{name:'Expanded form',formula:'Hundreds + Tens + Ones'},{name:'First four-digit number',formula:'999 + 1 = 1000'}]),

math2Chapter(2,'Number Operations','اعداد کے عمل','Pages 29–93',[
 math2Section('2.1','Addition of Three-Digit Numbers','Add ones, tens and hundreds in their columns. Regroup ten ones as one ten and ten tens as one hundred when needed.','اکائیوں، دہائیوں اور سیکڑوں کو ان کے خانوں میں جمع کریں۔ ضرورت ہو تو دس اکائیوں کو ایک دہائی اور دس دہائیوں کو ایک سیکڑا بنائیں۔',['Line up hundreds, tens and ones.','Carry/regroup to the next place when a column total is 10 or more.'],['سیکڑوں، دہائیوں اور اکائیوں کو سیدھ میں لکھیں۔','خانے کا حاصل ۱۰ یا زیادہ ہو تو اگلی جگہ پر ایک لے جائیں۔']),
 math2Section('2.2','Subtraction and Borrowing','Subtract ones, tens and hundreds in columns. If a top digit is smaller, regroup one from the next place: one ten becomes 10 ones, and one hundred becomes 10 tens.','اکائیوں، دہائیوں اور سیکڑوں کو خانوں میں منہا کریں۔ اگر اوپر کا ہندسہ چھوٹا ہو تو اگلی جگہ سے ایک لیں: ایک دہائی ۱۰ اکائیاں اور ایک سیکڑا ۱۰ دہائیاں بنتا ہے۔',['Subtract from right to left.','Check by adding the difference to the number subtracted.'],['دائیں سے بائیں منہا کریں۔','فرق کو منہا کیے گئے عدد میں جمع کرکے پڑتال کریں۔']),
 math2Section('2.3','Multiplication as Repeated Addition','Multiplication adds equal groups quickly. For example, 4 × 3 means four groups of three: 3 + 3 + 3 + 3 = 12. Learn the 2, 3, 4, 5 and 10 times tables.','ضرب برابر گروہوں کو جلد جمع کرنے کا طریقہ ہے۔ ۴ × ۳ کا مطلب تین کے چار گروہ ہے: ۳ + ۳ + ۳ + ۳ = ۱۲۔ ۲، ۳، ۴، ۵ اور ۱۰ کے پہاڑے سیکھیں۔',['The first factor tells how many groups.','Multiplication can be checked by repeated addition.'],['پہلا عدد گروہوں کی تعداد بتاتا ہے۔','ضرب کو بار بار جمع کرکے بھی سمجھا جا سکتا ہے۔']),
 math2Section('2.4','Division by Sharing and Grouping','Division shares objects equally or counts equal groups. 12 ÷ 3 asks how many groups of 3 make 12, or how many objects each get when 12 are shared among 3.','تقسیم چیزوں کو برابر بانٹتی یا برابر گروہ بناتی ہے۔ ۱۲ ÷ ۳ معلوم کرتا ہے کہ ۱۲ میں تین کے کتنے گروہ ہیں یا ۱۲ چیزیں تین بچوں میں بانٹنے پر ہر ایک کو کتنی ملیں گی۔',['Share one item at a time to keep groups equal.','Division is related to multiplication: 3 × 4 = 12, so 12 ÷ 3 = 4.'],['برابر گروہ بنانے کے لیے ایک ایک چیز بانٹیں۔','تقسیم ضرب سے متعلق ہے: ۳ × ۴ = ۱۲، اس لیے ۱۲ ÷ ۳ = ۴۔'])
],[
 {id:'m2e1',title:'Addition with Carrying',problem:'Add 268 + 157.',given:'268 + 157',method:'Add ones, tens and hundreds, regrouping as needed.',steps:['Ones: 8 + 7 = 15; write 5 and carry 1 ten.','Tens: 6 + 5 + 1 = 12; write 2 and carry 1 hundred.','Hundreds: 2 + 1 + 1 = 4.'],answer:'425'},
 {id:'m2e2',title:'Subtraction with Borrowing',problem:'Subtract 402 − 178.',given:'402 − 178',method:'Regroup hundreds and tens, then subtract by place.',steps:['Regroup 402 as 3 hundreds, 9 tens and 12 ones.','12 − 8 = 4; 9 − 7 = 2; 3 − 1 = 2.'],answer:'224'},
 {id:'m2e3',title:'Equal Groups',problem:'There are 5 plates with 4 biscuits on each. How many biscuits?',given:'5 groups of 4',method:'Multiply equal groups.',steps:['4 + 4 + 4 + 4 + 4 = 20.','So 5 × 4 = 20.'],answer:'20 biscuits'},
 {id:'m2e4',title:'Share Equally',problem:'Share 18 pencils equally among 3 children.',given:'18 pencils; 3 children',method:'Divide into equal groups.',steps:['Count 18 pencils into 3 equal groups.','Each group has 6 because 3 × 6 = 18.'],answer:'6 pencils each'}
],[{exercise:'2.1',title:'Exercise 2.1 — Addition',problems:[math2Problem('Q1','Add 347 + 286.','347 + 286 = 633.','633'),math2Problem('Q2','Add 408 + 175.','408 + 175 = 583.','583'),math2Problem('Q3','A library has 235 storybooks and 148 picture books. How many books altogether?','235 + 148 = 383.','383 books')]},{exercise:'2.2',title:'Exercise 2.2 — Subtraction',problems:[math2Problem('Q1','Subtract 600 − 248.','600 − 248 = 352.','352'),math2Problem('Q2','Subtract 731 − 426.','731 − 426 = 305.','305'),math2Problem('Q3','There are 425 apples. 178 are sold. How many remain?','425 − 178 = 247.','247 apples')]},{exercise:'2.3',title:'Exercise 2.3 — Multiplication',problems:[math2Problem('Q1','Write 4 groups of 5 as multiplication and find the product.','5 + 5 + 5 + 5 = 20, so 4 × 5 = 20.','20'),math2Problem('Q2','Find 3 × 7.','7 + 7 + 7 = 21.','21'),math2Problem('Q3','There are 6 boxes with 2 balls in each. How many balls?','6 × 2 = 12.','12 balls')]},{exercise:'2.4',title:'Exercise 2.4 — Division',problems:[math2Problem('Q1','Share 20 sweets equally among 5 children.','20 ÷ 5 = 4.','4 sweets each'),math2Problem('Q2','How many groups of 3 are in 18?','18 ÷ 3 = 6 because 3 × 6 = 18.','6 groups'),math2Problem('Q3','Divide 16 pencils equally into 4 cups.','16 ÷ 4 = 4.','4 pencils per cup')]}],{
 mcqs:[{q:'What is 245 + 130?',options:['365','375','385','275'],correct:1,exp:'245 + 130 = 375.'},{q:'What is 500 − 175?',options:['325','335','425','375'],correct:0,exp:'500 − 175 = 325.'},{q:'What is 4 × 3?',options:['7','10','12','16'],correct:2,exp:'Four groups of three make 12.'},{q:'12 ÷ 4 = ?',options:['2','3','4','8'],correct:1,exp:'Three groups of 4 make 12.'}],
 shortQuestions:[{q:'Write 3 groups of 4 as repeated addition.',sol:'4 + 4 + 4 = 12.'},{q:'Find 36 ÷ 6.',sol:'36 ÷ 6 = 6 because 6 × 6 = 36.'},{q:'How can you check 74 − 29 = 45?',sol:'Add 45 + 29. It equals 74, so the subtraction is correct.'}],
 longQuestions:[{q:'Solve 356 + 287 and show regrouping.',marks:4,rubric:'Correct column addition and regrouping.',sol:'Ones: 6 + 7 = 13; write 3, carry 1. Tens: 5 + 8 + 1 = 14; write 4, carry 1. Hundreds: 3 + 2 + 1 = 6. Answer: 643.'},{q:'There are 24 balloons shared equally among 4 children. Show the division using multiplication.',marks:3,rubric:'Represent equal sharing and state the quotient.',sol:'24 ÷ 4 = 6. Check: 4 × 6 = 24. Each child gets 6 balloons.'}]},[{name:'Addition check',formula:'Addends → Sum'},{name:'Subtraction check',formula:'Difference + subtracted number = starting number'},{name:'Multiplication',formula:'Equal groups → repeated addition'},{name:'Division check',formula:'Divisor × Quotient = Dividend'}]),

math2Chapter(3,'Fractions','کسر','Pages 94–107',[
 math2Section('3.1','Equal Parts and Fractions','A fraction names equal parts of one whole. The denominator tells the number of equal parts; the numerator tells how many parts are selected.','کسر ایک مکمل چیز کے برابر حصے بتاتا ہے۔ نیچے کا عدد برابر حصوں کی تعداد اور اوپر کا عدد لیے گئے حصوں کی تعداد بتاتا ہے۔',['Parts must be equal in size.','Write numerator above the fraction bar and denominator below it.'],['حصے برابر ہونے چاہئیں۔','اوپر شمار کنندہ اور نیچے مخرج لکھیں۔']),
 math2Section('3.2','One-Half, One-Third and One-Quarter','One-half means 1 of 2 equal parts (1/2); one-third means 1 of 3 equal parts (1/3); one-quarter means 1 of 4 equal parts (1/4).','آدھا ۲ برابر حصوں میں سے ۱ حصہ (۱/۲)، تہائی ۳ میں سے ۱ حصہ (۱/۳)، اور چوتھائی ۴ میں سے ۱ حصہ (۱/۴) ہے۔',['Share or divide the whole into equal parts first.','The same fraction can be shown with a shape or a group of objects.'],['پہلے مکمل چیز کو برابر حصوں میں بانٹیں۔','ایک ہی کسر شکل یا چیزوں کے گروہ سے دکھائی جا سکتی ہے۔']),
 math2Section('3.3','Fractions in Pictures','Colour or identify equal parts in circles, rectangles and other shapes. A coloured part is only a fraction when the whole is divided into equal parts.','دائروں، مستطیلوں اور دوسری شکلوں کے برابر حصوں کو رنگیں یا پہچانیں۔ رنگا ہوا حصہ تب کسر بنتا ہے جب مکمل شکل برابر حصوں میں تقسیم ہو۔',['Count all equal parts to name the denominator.','Count coloured parts to name the numerator.'],['مخرج معلوم کرنے کے لیے تمام برابر حصے گنیں۔','شمار کنندہ معلوم کرنے کے لیے رنگے حصے گنیں۔'])
],[{id:'m2e1',title:'Name the Fraction',problem:'A circle is divided into 4 equal parts. One part is coloured. Name the fraction.',given:'4 equal parts; 1 coloured',method:'Parts coloured over total equal parts.',steps:['There is 1 coloured part.','There are 4 equal parts altogether.'],answer:'1/4 (one-quarter)'},{id:'m2e2',title:'Find One-Half',problem:'Find one-half of 8 counters.',given:'8 counters',method:'Split into two equal groups.',steps:['8 ÷ 2 = 4.','Each half has 4 counters.'],answer:'4 counters'}],[{exercise:'3.1',title:'Exercise 3.1 — Fractions',problems:[math2Problem('Q1','Write the fraction for 1 part out of 3 equal parts.','One of three equal parts is 1/3.','1/3'),math2Problem('Q2','How many equal parts make one-half?','One-half divides the whole into 2 equal parts.','2 parts'),math2Problem('Q3','Find one-quarter of 12.','12 ÷ 4 = 3.','3'),math2Problem('Q4','A shape has 4 equal parts and 3 are coloured. What fraction is coloured?','3 of 4 parts are coloured.','3/4')]}],{
 mcqs:[{q:'One-half is written as:',options:['1/2','1/3','1/4','2/1'],correct:0,exp:'One-half is one of two equal parts: 1/2.'},{q:'The bottom number in a fraction tells:',options:['coloured parts','total equal parts','the colour','the shape'],correct:1,exp:'The denominator is the total number of equal parts.'},{q:'One-quarter means one of how many equal parts?',options:['2','3','4','5'],correct:2,exp:'A quarter is one of four equal parts.'},{q:'One-third of 9 is:',options:['2','3','4','6'],correct:1,exp:'9 ÷ 3 = 3.'}],
 shortQuestions:[{q:'What is the denominator?',sol:'The denominator is the bottom number. It tells how many equal parts make the whole.'},{q:'Find one-half of 10.',sol:'10 ÷ 2 = 5.'},{q:'What must be true about the parts in a fraction picture?',sol:'The whole must be divided into equal-sized parts.'}],
 longQuestions:[{q:'Explain how to show 3/4 on a shape.',marks:3,rubric:'Divide into four equal parts and identify three.',sol:'Divide a shape into 4 equal parts. Colour 3 parts. The coloured fraction is 3/4.'},{q:'A cake is cut into 3 equal pieces. One piece is eaten. What fraction was eaten and what fraction remains?',marks:4,rubric:'Name the eaten part and the remaining equal parts.',sol:'One of the 3 equal pieces was eaten, so 1/3 was eaten. Two pieces remain, so 2/3 remains.'}]},[{name:'Fraction',formula:'Numerator / Denominator'},{name:'Half',formula:'1/2 of a number = divide by 2'},{name:'Quarter',formula:'1/4 of a number = divide by 4'}]),

math2Chapter(4,'Measurement: Length, Mass and Capacity','پیمائش: لمبائی، کمیت اور گنجائش','Pages 108–127',[
 math2Section('4.1','Length: Metres and Centimetres','Length tells how long or tall something is. Use centimetres (cm) for shorter objects and metres (m) for longer distances or heights. 100 cm = 1 m.','لمبائی بتاتی ہے کہ کوئی چیز کتنی لمبی یا اونچی ہے۔ چھوٹی چیزوں کے لیے سینٹی میٹر اور زیادہ لمبی چیزوں کے لیے میٹر استعمال کریں۔ ۱۰۰ سینٹی میٹر = ۱ میٹر۔',['Measure from zero on the ruler.','Use the same unit when comparing lengths.'],['اسکیل پر صفر سے پیمائش کریں۔','لمبائیوں کا موازنہ کرتے وقت ایک ہی اکائی استعمال کریں۔']),
 math2Section('4.2','Mass: Kilograms and Grams','Mass tells how heavy an object is. Use grams (g) for lighter things and kilograms (kg) for heavier things. 1000 g = 1 kg.','کمیت بتاتی ہے کہ کوئی چیز کتنی بھاری ہے۔ ہلکی چیزوں کے لیے گرام اور بھاری چیزوں کے لیے کلوگرام استعمال کریں۔ ۱۰۰۰ گرام = ۱ کلوگرام۔',['Use a balance or weighing scale to compare mass.','Write the unit with the measurement.'],['کمیت کا موازنہ ترازو سے کریں۔','پیمائش کے ساتھ اکائی ضرور لکھیں۔']),
 math2Section('4.3','Capacity: Litres and Millilitres','Capacity is how much liquid a container can hold. Use litres (L) for larger amounts and millilitres (mL) for small amounts. 1000 mL = 1 L.','گنجائش بتاتی ہے کہ برتن میں کتنا مائع آ سکتا ہے۔ زیادہ مقدار کے لیے لیٹر اور کم مقدار کے لیے ملی لیٹر استعمال کریں۔ ۱۰۰۰ ملی لیٹر = ۱ لیٹر۔',['A larger container can hold more liquid.','Keep units the same before adding or subtracting.'],['بڑا برتن زیادہ مائع رکھ سکتا ہے۔','جمع یا تفریق سے پہلے اکائیاں ایک جیسی کریں۔']),
 math2Section('4.4','Adding and Subtracting Measurements','Add or subtract measurements written in the same unit. Line up place values and include the unit in the answer.','ایک ہی اکائی میں لکھی پیمائشوں کو جمع یا منہا کریں۔ جگہ کی قدر سیدھ میں رکھیں اور جواب میں اکائی لکھیں۔',['Convert to the same unit before calculating.','Check whether the answer is reasonable.'],['حساب سے پہلے پیمائشوں کو ایک ہی اکائی میں بدلیں۔','دیکھیں کہ جواب مناسب ہے۔'])
],[{id:'m2e1',title:'Convert Metres and Centimetres',problem:'Change 2 m to centimetres.',given:'1 m = 100 cm',method:'Multiply metres by 100.',steps:['2 × 100 = 200.'],answer:'200 cm'},{id:'m2e2',title:'Compare Mass',problem:'A bag weighs 2 kg and a box weighs 1500 g. Which is heavier?',given:'2 kg and 1500 g',method:'Convert to the same unit.',steps:['2 kg = 2000 g.','2000 g is more than 1500 g.'],answer:'The bag is heavier.'}],[{exercise:'4.1',title:'Exercise 4.1 — Length',problems:[math2Problem('Q1','How many centimetres are in 3 m?','3 × 100 = 300 cm.','300 cm'),math2Problem('Q2','Add 45 cm + 32 cm.','45 + 32 = 77 cm.','77 cm')]},{exercise:'4.2',title:'Exercise 4.2 — Mass and Capacity',problems:[math2Problem('Q1','How many grams are in 2 kg?','2 × 1000 = 2000 g.','2000 g'),math2Problem('Q2','Add 250 mL + 500 mL.','250 + 500 = 750 mL.','750 mL'),math2Problem('Q3','A bottle holds 1 L. How many millilitres is that?','1 L = 1000 mL.','1000 mL')]}],{
 mcqs:[{q:'100 cm equals:',options:['1 m','10 m','100 m','1 km'],correct:0,exp:'100 centimetres make 1 metre.'},{q:'Which unit suits the mass of a watermelon?',options:['kg','cm','mL','minute'],correct:0,exp:'A watermelon is heavy, so kilograms are suitable.'},{q:'1000 mL equals:',options:['1 L','10 L','100 L','1 kg'],correct:0,exp:'1000 millilitres make 1 litre.'},{q:'A ruler is used to measure:',options:['length','mass','time','capacity'],correct:0,exp:'A ruler measures length.'}],
 shortQuestions:[{q:'Which unit is shorter: metre or centimetre?',sol:'A centimetre is shorter than a metre.'},{q:'How many grams make 1 kilogram?',sol:'1000 grams make 1 kilogram.'},{q:'Name the unit used for liquid capacity.',sol:'Litres (L) and millilitres (mL) measure capacity.'}],
 longQuestions:[{q:'A ribbon is 1 m long. How many centimetres is it? If 35 cm is cut off, how much remains?',marks:4,rubric:'Convert metres to centimetres, then subtract.',sol:'1 m = 100 cm. 100 − 35 = 65 cm remains.'},{q:'Explain which units you would use to measure a pencil, a sack of rice and a jug of water.',marks:3,rubric:'Choose sensible units for length, mass and capacity.',sol:'Measure a pencil in centimetres (cm), a sack of rice in kilograms (kg), and water in litres (L) or millilitres (mL).'}]},[{name:'Length',formula:'100 cm = 1 m'},{name:'Mass',formula:'1000 g = 1 kg'},{name:'Capacity',formula:'1000 mL = 1 L'}]),

math2Chapter(5,'Time','وقت','Pages 128–140',[
 math2Section('5.1','Hours and Minutes','A clock has an hour hand and a minute hand. The short hand shows hours; the long hand shows minutes. One hour has 60 minutes.','گھڑی میں گھنٹے اور منٹ کی سوئیاں ہوتی ہیں۔ چھوٹی سوئی گھنٹے اور لمبی سوئی منٹ بتاتی ہے۔ ایک گھنٹے میں ۶۰ منٹ ہوتے ہیں۔',['Read the short hand for the hour and the long hand for minutes.','The long hand moves around the clock once in an hour.'],['چھوٹی سوئی سے گھنٹہ اور لمبی سوئی سے منٹ پڑھیں۔','لمبی سوئی ایک گھنٹے میں گھڑی کا ایک چکر لگاتی ہے۔']),
 math2Section('5.2','Reading and Writing Time','Write digital time with hours and minutes, such as 3:20. Read the minute hand by counting in fives around the clock.','ڈیجیٹل وقت گھنٹے اور منٹ کے ساتھ لکھیں، جیسے ۳:۲۰۔ منٹ کی سوئی پڑھنے کے لیے گھڑی پر پانچ پانچ گنیں۔',['Each number on the clock is 5 minutes apart for the minute hand.','Use a colon between hours and minutes.'],['منٹ کی سوئی کے لیے گھڑی کے ہر عدد کے درمیان ۵ منٹ ہیں۔','گھنٹوں اور منٹوں کے درمیان دو نقطے لگائیں۔']),
 math2Section('5.3','a.m. and p.m.','Use a.m. for times from midnight to before noon and p.m. for times from noon to before midnight. Think about whether an activity happens in the morning or evening.','آدھی رات سے دوپہر سے پہلے تک کے وقت کے لیے a.m. اور دوپہر سے آدھی رات سے پہلے تک کے وقت کے لیے p.m. استعمال کریں۔ سوچیں کہ کام صبح ہوتا ہے یا شام۔',['12:00 noon is midday; 12:00 midnight starts a new day.','Use the activity to help decide a.m. or p.m.'],['۱۲:۰۰ دوپہر کا وقت ہے اور ۱۲:۰۰ آدھی رات نیا دن شروع کرتی ہے۔','a.m. یا p.m. چننے کے لیے سرگرمی کے وقت پر غور کریں۔']),
 math2Section('5.4','Solar and Lunar Calendars','A solar calendar has 365 days in a common year and 12 months. The lunar calendar follows the moon and also has 12 months. Use a calendar to read dates and days.','عام شمسی سال میں ۳۶۵ دن اور ۱۲ مہینے ہوتے ہیں۔ قمری کیلنڈر چاند کے مطابق ہوتا ہے اور اس کے بھی ۱۲ مہینے ہیں۔ تاریخ اور دن پڑھنے کے لیے کیلنڈر دیکھیں۔',['Read across a calendar week to find the day.','Months have different numbers of days.'],['دن معلوم کرنے کے لیے کیلنڈر میں ہفتے کی قطار دیکھیں۔','مہینوں میں دنوں کی تعداد مختلف ہو سکتی ہے۔'])
],[{id:'m2e1',title:'Read the Clock',problem:'The hour hand is at 4 and the minute hand at 6. What time is shown?',given:'Hour = 4; minute hand = 6',method:'Count 5 minutes for each number passed by the minute hand.',steps:['The minute hand at 6 means 30 minutes.','Read the hour hand: 4.'],answer:'4:30 (half past four)'},{id:'m2e2',title:'Choose a.m. or p.m.',problem:'A child eats breakfast at 7 in the morning. Write the time with a.m. or p.m.',given:'7 in the morning',method:'Morning times use a.m.',steps:['It is morning, before noon.'],answer:'7:00 a.m.'}],[{exercise:'5.1',title:'Exercise 5.1 — Time',problems:[math2Problem('Q1','Write “quarter past 3” as digital time.','Quarter past means 15 minutes after 3.','3:15'),math2Problem('Q2','Write “half past 8” as digital time.','Half past means 30 minutes after 8.','8:30'),math2Problem('Q3','Which is later: 9:15 a.m. or 9:45 a.m.?','At the same hour, 45 minutes is later than 15 minutes.','9:45 a.m.'),math2Problem('Q4','How many minutes are in 2 hours?','2 × 60 = 120 minutes.','120 minutes')]}],{
 mcqs:[{q:'One hour has how many minutes?',options:['30','45','60','100'],correct:2,exp:'One hour has 60 minutes.'},{q:'Quarter past 5 is:',options:['5:15','5:30','5:45','6:15'],correct:0,exp:'A quarter hour is 15 minutes.'},{q:'Which time is in the evening?',options:['8:00 a.m.','10:00 a.m.','7:00 p.m.','9:00 a.m.'],correct:2,exp:'p.m. is used after noon; 7 p.m. is evening.'},{q:'The minute hand points to 3. How many minutes past the hour?',options:['3','15','30','45'],correct:1,exp:'Each clock number is 5 minutes: 3 × 5 = 15.'}],
 shortQuestions:[{q:'What does the short hand show?',sol:'The short hand shows the hour.'},{q:'Write half past 6 as digital time.',sol:'Half past 6 is 6:30.'},{q:'When do we use p.m.?',sol:'Use p.m. for times from noon until before midnight.'}],
 longQuestions:[{q:'Explain how to read 7:45 on an analogue clock.',marks:4,rubric:'Read the hour and count the minute hand in fives.',sol:'The short hand is between 7 and 8. The long hand points to 9, which is 9 × 5 = 45 minutes. The time is 7:45.'},{q:'Write one morning and one evening activity and show an appropriate time with a.m. or p.m.',marks:3,rubric:'Give sensible activities and label morning/evening times.',sol:'Sample: I go to school at 8:00 a.m. I eat dinner at 7:00 p.m.'}]},[{name:'Time',formula:'1 hour = 60 minutes'},{name:'Clock',formula:'Minute hand: each number = 5 minutes'},{name:'Calendar',formula:'Solar year = 12 months'}]),

math2Chapter(6,'Geometry','جیومیٹری','Pages 141–158',[
 math2Section('6.1','Two-Dimensional and Three-Dimensional Shapes','Flat shapes are 2-D, such as a circle, triangle, square and rectangle. Solid shapes are 3-D, such as a cube, cuboid, sphere, cone and cylinder.','چپٹی شکلیں دو بُعدی ہوتی ہیں، جیسے دائرہ، مثلث، مربع اور مستطیل۔ ٹھوس شکلیں تین بُعدی ہوتی ہیں، جیسے مکعب، مکعب مستطیل، کرہ، مخروط اور سلنڈر۔',['A cube has flat square faces.','A sphere is round like a ball.'],['مکعب کے چپٹے مربع رخ ہوتے ہیں۔','کرہ گیند کی طرح گول ہوتا ہے۔']),
 math2Section('6.2','Sides, Vertices and Circles','A side is a straight boundary of a shape. A vertex is a corner where sides meet. A circle can be divided into two semicircles or four quarter-circles.','شکل کی سیدھی حد کو ضلع کہتے ہیں۔ جہاں اضلاع ملیں وہ کونا یا رأس ہے۔ دائرے کو دو نصف دائروں یا چار چوتھائی دائروں میں بانٹا جا سکتا ہے۔',['Count each side and corner once.','Equal parts of a circle must have the same size.'],['ہر ضلع اور کونے کو ایک بار گنیں۔','دائرے کے برابر حصوں کا سائز یکساں ہوتا ہے۔']),
 math2Section('6.3','Straight and Curved Lines','A straight line does not bend. A curved line bends. Shapes and pictures can be made by combining both kinds of lines.','سیدھی لکیر مڑتی نہیں۔ خم دار لکیر مڑتی ہے۔ دونوں طرح کی لکیریں ملا کر شکلیں اور تصویریں بنائی جا سکتی ہیں۔',['Use a ruler to draw a straight line.','Look for bends to identify curved lines.'],['سیدھی لکیر بنانے کے لیے اسکیل استعمال کریں۔','خم دیکھ کر خم دار لکیر پہچانیں۔']),
 math2Section('6.4','Patterns and Position on a Grid','A pattern repeats a shape, colour, direction or arrangement. Continue a grid pattern by following the same rule in each square.','نمونہ شکل، رنگ، سمت یا ترتیب کو دہراتا ہے۔ ہر خانے میں وہی قاعدہ جاری رکھ کر جالی کا نمونہ مکمل کریں۔',['Find the repeating part before drawing.','Keep rows and columns aligned on the grid.'],['بنانے سے پہلے دہرائے جانے والے حصے کو پہچانیں۔','جالی میں قطاروں اور خانوں کو سیدھ میں رکھیں۔']),
 math2Section('6.5','Roman Numerals','Roman numerals use letters as number symbols. In the workbook, learn the listed numerals and match each symbol to its number.','رومن اعداد میں حروف کو عددی علامت کے طور پر استعمال کیا جاتا ہے۔ کتاب میں دی گئی علامات سیکھیں اور ہر علامت کو اس کے عدد سے ملائیں۔',['I = 1, V = 5 and X = 10.','Read the symbols in the order shown in the table.'],['I = ۱، V = ۵ اور X = ۱۰۔','جدول میں دی گئی ترتیب کے مطابق علامات پڑھیں۔'])
],[{id:'m2e1',title:'Name the Solid',problem:'Which solid shape looks like a ball?',given:'A ball is round in every direction.',method:'Match the object to a 3-D shape.',steps:['A ball has a round surface and no flat face.'],answer:'Sphere'},{id:'m2e2',title:'Sides and Vertices',problem:'How many sides and vertices does a triangle have?',given:'Triangle',method:'Count the straight sides and corners.',steps:['A triangle has 3 straight sides.','The sides meet at 3 corners.'],answer:'3 sides and 3 vertices'}],[{exercise:'6.1',title:'Exercise 6.1 — Geometry',problems:[math2Problem('Q1','Name a 3-D shape that looks like a can.','A can has two circular ends and one curved surface.','Cylinder'),math2Problem('Q2','How many vertices does a rectangle have?','A rectangle has four corners.','4'),math2Problem('Q3','What is one-half of a circle called?','One-half of a circle is a semicircle.','Semicircle'),math2Problem('Q4','Name the line that bends.','A line that bends is a curved line.','Curved line'),math2Problem('Q5','What is the Roman numeral for 5?','V represents 5.','V')]}],{
 mcqs:[{q:'Which is a 3-D shape?',options:['Triangle','Square','Cube','Circle'],correct:2,exp:'A cube is a solid 3-D shape.'},{q:'A shape corner is called a:',options:['side','vertex','curve','face'],correct:1,exp:'A vertex is a corner where sides meet.'},{q:'One-half of a circle is a:',options:['quarter-circle','semicircle','triangle','cube'],correct:1,exp:'A semicircle is half of a circle.'},{q:'Which line bends?',options:['straight line','curved line','side','vertex'],correct:1,exp:'A curved line bends.'}],
 shortQuestions:[{q:'Name two 3-D shapes.',sol:'Any two: cube, cuboid, sphere, cone or cylinder.'},{q:'How many equal parts make a quarter-circle?',sol:'A circle divided into four equal parts makes quarter-circles.'},{q:'What is the Roman numeral V?',sol:'V represents 5.'}],
 longQuestions:[{q:'Describe a square and a cube. How are they different?',marks:4,rubric:'Describe the square as flat and cube as solid, including basic features.',sol:'A square is a flat 2-D shape with 4 equal sides and 4 vertices. A cube is a solid 3-D shape with 6 square faces, edges and vertices.'},{q:'Explain how to make and continue a simple shape pattern on a grid.',marks:3,rubric:'Describe finding and repeating the pattern rule.',sol:'Look for the group of shapes or colours that repeats. Copy the group in the same order into the next grid squares, keeping rows and columns aligned.'}]},[{name:'2-D',formula:'Flat shapes: circle, triangle, square, rectangle'},{name:'3-D',formula:'Solid shapes: cube, cuboid, sphere, cone, cylinder'},{name:'Circle parts',formula:'2 halves = 2 semicircles · 4 quarters = 4 quarter-circles'}])
];
